<div class="row">
<?php
// module/Admin/view/user/add.phtml:

$title = 'Add new User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="control-group col-md-4">  
    <div class="form-group">
        <?php echo $this->formLabel($form->get('first_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('first_name')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('last_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('last_name')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('middle_init')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('middle_init')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('user_roles')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formMultiCheckbox($form->get('user_roles')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formInput($form->get('id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div>