<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'user')); ?>
<?php
$title = 'Add new User';
$this->headTitle($title);
?>
<div class="row user-content">
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-12" style="overflow:hidden;">
    <div class="col-md-8">
    <?php echo $this->partial('admin/user/form.phtml',array('form'=>$this->form,'action' =>'add','submitVal' =>'Add User', 'id' => $this->id));?>
    </div>
</div>
</div>