<div class="row">
<?php
// module/Admin/view/user/edit.phtml:

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="col-md-12" style="overflow:hidden;">
    <div class="col-md-4">  
        <div class="form-group row">
            <?php echo $this->formLabel($form->get('first_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('first_name')); ?>
        </div>
        <div class="form-group row">
            <?php echo $this->formLabel($form->get('last_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('last_name')); ?>
        </div>
        <div class="form-group row">
            <?php echo $this->formLabel($form->get('middle_init')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('middle_init')); ?>
        </div>
        <div class="form-group row">
            <?php echo $this->formLabel($form->get('email')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('email')); ?>
        </div>
        <div class="form-group row">
            <?php echo $this->formLabel($form->get('user_roles')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formMultiCheckbox($form->get('user_roles')); ?>
        </div>
        <div class="form-group row">
            <?php echo $this->formInput($form->get('id')); ?>
        </div>
    </div>
    <div class=" col-md-8">
        <p>Assign user to unit</p>
    </div>
</div>
<div class="col-md-12">
    <div class="control-group">
        <div class="form-group"><?php echo $this->formSubmit($form->get('submit')); ?></div>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
</div>
