<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user', array('action' => $action,'id'=>$this->id)));
    $form->prepare();

    echo $this->form()->openTag($form);
  ?>
<div class="control-group col-md-12">  
    <div class="col-md-3">  
        <div class="form-group col-md-12 first-name">
            <?php echo $this->formLabel($form->get('first_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('first_name')); ?>
        </div>
                <div class="form-group col-md-12 middle-init">
            <?php echo $this->formLabel($form->get('middle_init')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('middle_init')); ?>
        </div>
    </div>
    <div class="col-md-3"> 
        <div class="form-group col-md-12 last-name">
            <?php echo $this->formLabel($form->get('last_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('last_name')); ?>
        </div>
        <div class="form-group col-md-12 email">
            <?php echo $this->formLabel($form->get('email')->setLabelAttributes(array('class'=>'control-label'))); ?>
            <?php echo $this->formInput($form->get('email')); ?>
        </div>
    </div>
    <div class="col-md-3"> 
        <div class="form-group col-md-12 user-roles-wrapper">
            <label class="control-label head-label">Roles</label>
            <div class="user-roles-container">
                <?php 
                     for($i=0; $i<$this->count; $i++)
                    {
                         echo $this->formSelect($form->get('role_'.$i)->setLabelAttributes(array('class'=>'control-label ')));
                    }
                ?>
            </div>
        </div>

    </div> 
    <div class="col-md-3"> 
        <div class="form-group col-md-12 user-role-options-placeholder">
            <?php  echo $this->formSelect($form->get('liaison_privs'));
                 echo $this->formSelect($form->get('unit_privs')); 
              ?>
        </div>
        <div class="form-group col-md-12 submit">
            <?php echo $this->formSubmit($form->get('submit')->setValue($submitVal)); ?>
        </div>
        <?php if($action == 'edit'): ?>
            <div class="form-group col-md-12 add-new-role-wrapper">
                <button type="button" class="btn btn-primary add-new-role">Add Role</button>
            </div>
        <?php endif; ?>
    </div>
    
    
    <!--- some ajaxy thing to generate the assessors and liasons privs -->
    
</div>
<?php echo $this->formInput($form->get('id')); ?> 
<?php echo $this->form()->closeTag(); ?>


<script>
  $( document ).ready(function() {
      initPrivs();
      initRoles();

      
      $('.add-new-role').click(function(){
         if($('#role_1').hasClass('hide')){
              $('#role_1').removeClass('hide');
          }else if($('#role_2').hasClass('hide')){
              $('#role_2').removeClass('hide');
          }else{
              $('#role_3').removeClass('hide');
          }
      });
      
      $('.user-roles').on("change", function () { 
          var roles = [];
          $('.user-roles').each(function(){
            var role= $(this);
            roles.push(role.val());
          });
           if(jQuery.inArray( "2", roles) > -1){
                $('#unit_privs').removeClass('hide');
                $('#unit_privs').prop("disabled",false);
            }else{
                $('#unit_privs').addClass('hide');
                $('#unit_privs').prop("disabled",true);
                $('#unit_privs:selected').removeAttr("selected");
            }
            if(jQuery.inArray( "4", roles)  > -1 ){
                $('#liaison_privs').removeClass('hide');
                $('#liaison_privs').prop("disabled",false);
            }else{
                $('#liaison_privs').addClass('hide');
                $('#liaison_privs').prop("disabled",true);
                $('#liaison_privs:selected').removeAttr("selected");
            }
          
          
      });
      
      function initPrivs()
      {
         var roles = [];
          
          $('.user-roles').each(function(){
            var role= $(this);
            roles.push(role.val());
          });
          
           if(jQuery.inArray( "2", roles) > -1){
                $('#unit_privs').removeClass('hide');
                $('#unit_privs').prop("disabled",false);
            }else{
                $('#unit_privs').addClass('hide');
                $('#unit_privs').prop("disabled",true);
                $('#unit_privs:selected').removeAttr("selected");
            }
            if(jQuery.inArray( "4", roles)  > -1 ){
                $('#liaison_privs').removeClass('hide');
                $('#liaison_privs').prop("disabled",false);
            }else{
                $('#liaison_privs').addClass('hide');
                $('#liaison_privs').prop("disabled",true);
                $('#liaison_privs:selected').removeAttr("selected");
            }
      }
      
      function initRoles()
      {
          if(!$('#role_1').val()){
              $('#role_1').addClass('hide');
          }
          if(!$('#role_2').val()){
              $('#role_2').addClass('hide');
          }
          if(!$('#role_3').val()){
              $('#role_3').addClass('hide');
          }
      }
      
}); 
    
</script>