<?php
// module/Admin/view/admin/user/index.phtml:
$title = 'Users';
$this->headTitle($title);
?>
<div class="col-md-12">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
</div>

<div class="control-group col-md-12" style="overflow:hidden;">
 <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
  ?>

    <h4>Add a new user</h4>
    <div class="form-group col-md-2">
        <?php echo $this->formLabel($form->get('first_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('first_name')); ?>
    </div>
    <div class="form-group col-md-2">
        <?php echo $this->formLabel($form->get('last_name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('last_name')); ?>
    </div>
    <div class="form-group col-md-2">
        <?php echo $this->formLabel($form->get('middle_init')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('middle_init')); ?>
    </div>
    <div class="form-group col-md-2">
        <?php echo $this->formLabel($form->get('email')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('email')); ?>
    </div>
    <div class="form-group col-md-8">
        <?php echo $this->formLabel($form->get('user_roles')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formMultiCheckbox($form->get('user_roles')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formInput($form->get('id')); ?>
    </div>
    <div class="form-group col-md-4">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>

<?php echo $this->form()->closeTag(); ?>
</div>

<div class="col-md-12">
    <div class="table-responsive">
            <colgroup>
                <col class="col-xs-8">
            </colgroup>
            <?php // add at the end of the file after the table
                    echo $this->paginationControl(
                        // the paginator object
                        $this->paginator,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('admin/user/controls.phtml', 'User'),
                        // the route to link to when a user clicks a control link
                        array(
                            'route' => 'user'
                        )
                    );
                    ?>
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Middle Int.</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $user) : ?>
                        <tr class="active">
                                    <td><?php echo $this->escapeHtml($user->id);?></td>
                                   <td><?php echo $this->escapeHtml($user->first_name);?></td>
                                    <td><?php echo $this->escapeHtml($user->last_name);?></td>
                                    <td><?php echo $this->escapeHtml($user->middle_init);?></td>
                                    <td><?php echo $this->escapeHtml($user->email);?></td>
                                    <td>
                                        <?php foreach ($user->user_roles as $row => $role) : ?>
                                            <?php echo $this->escapeHtml($role['term']);?>
                                        <?php endforeach; ?>
                                        
                                    </td>    
                                    <td>
                                        <a class="btn btn-primary btn-xs" href="<?php echo $this->url('user',
                                            array('action'=>'edit', 'id' => $user->id));?>"><?php echo $this->translate ('Edit') ?> &raquo;</a>
                                        <a class="btn btn-warning btn-xs" href="<?php echo $this->url('user',
                                            array('action'=>'delete', 'id' => $user->id));?>"><?php echo $this->translate ('Delete') ?> &raquo;</a>
                                    </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
                <?php // add at the end of the file after the table
                    echo $this->paginationControl(
                        // the paginator object
                        $this->paginator,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('admin/user/controls.phtml', 'User'),
                        // the route to link to when a user clicks a control link
                        array(
                            'route' => 'user'
                        )
                    );
                    ?>
    </div>
</div>

