<?php
// module/Admin/view/admin/user/index.phtml:
$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>



<table class="table">
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Middle Int.</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->first_name);?></td>
    <td><?php echo $this->escapeHtml($user->last_name);?></td>
    <td><?php echo $this->escapeHtml($user->middle_init);?></td>

</tr>
<?php endforeach; ?>
</table>
