<?php
$form->setAttribute('action', $this->url('user',array('action' => 'newuser')))
     ->prepare();

echo $this->form()->openTag($form);

$user = $form->get('userobj');


echo $this->formRow($user->get('firstname'));
echo $this->formRow($user->get('lastname'));
echo $this->formRow($user->get('middleinit'));
echo $this->formRow($user->get('email'));

echo $this->formCollection($user->get('roles'));?>
<div class="unit-priv-fieldset">
    <?php echo $this->formCollection($user->get('unitprivs')); ?>
</div>
<button onclick="return add_unit_priv()">Add a new unit priv</button>
<script>
    function add_unit_priv() {
        var currentCount = $('form > .unit-priv-fieldset > fieldset > fieldset ').length;
        console.log(currentCount);
        var template = $('form > .unit-priv-fieldset > fieldset > span').data('template');

        template = template.replace(/__index__/g, currentCount);
        $('form > .unit-priv-fieldset  > fieldset').append(template);
        return false;
    }
</script>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();