<?php

// module/Mock/view/mock/mock/add.phtml:

$title = 'Add New Assessment Report';
$this->headTitle($title);
?>	
<html>
    <body>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="../css/bootstrap.min.css"> 
    <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
    <style>
        textarea {
            width: 300px;
        }</style>
	<div class="container">
	<center><h3>Assessment Reports</h3>
            
	    </center>
	    
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
                       
	<p></p>
                        <h6>Department Name</h6>
                       
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science</a></li>
                                    <li><a href="#">Science</a></li>
                                    <li><a href="#">Math</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Prog/Degree dropdown -->
                        <h6>Degree/Program</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="MS/Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    
				    <li><a href="#">BS/Computer Science</a></li>
                                    <li><a href="#">MS/Computer Science</a></li>
                                    <li><a href="#">MA/Computer Science</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year --> <h6>Academic Year</h6>
			<div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="2014-15">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">

                                    <span data-bind="label">Select</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>
                            </div>			    
                        </div><p></p>
			
	  <!-- Get Button trigger modal -->
<a class="btn btn-primary btn-md" href="./reports/viewAllReports">
  View Reports &raquo;
</a>
<a class="btn btn-primary btn-md btn" href="./reports/addReport">
  Add New &raquo;
</a>
<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>
                    </div><!--close container-->
                </div><!--close column-->
		
		<!--column 2-->
		
	</div>
	 <script src="../js/bootstrap.min.js"></script>
                        <script src="../js/jquery.min.js"></script>
                        <script src="../js/bootstrap3-typeahead.js"></script>
                        <script src="https://code.jquery.com/jquery.js"></script>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script src="../js/bootstrap-rta.min.js"></script>
                        <script>
                            $(document).ready(function() {
                                document.getElementById('ta_sample').value = "";
                                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
                            });
                        </script>
    </body>
</html>










