<?php


$title = 'Assessment Report Index';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html lang="en">

<head>
     <link rel="stylesheet" href="./css/bootstrap.css"> 
    <link rel="stylesheet" href="./css/bootstrap-rta.min.css">
	    <link rel="stylesheet" href="./css/bootstrap-select.css">
	    <link rel="stylesheet" href="./css/bootstrap-select.css">
    
</head>
    <body>  <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <style>
        textarea {
            width: 300px;
        }</style>
	<div class="container">
	<center><h3>Assessment Reports</h3>
            
	    </center>
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
                       
	<p></p>
       <!-- Choose Action -->
      <select class="selectpicker" id="action-menu" data-style="btn-primary" title='Choose Action'>
         <option data-hidden="true"></option>
      </select>  
     <br />
     <br />
   
      <!-- Choose Department/Unit -->
      <select class="selectpicker" id="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
         <option data-hidden="true"></option>
      </select>  
     <br />
     <br />
   
      <!-- Choose Program/Degree -->
      <select class="selectpicker" id="prog-menu" data-style="btn-primary" title='Choose Program/Degree' multiple>
	 <option data-hidden="true"></option>
        

      </select>
     <br />
     <br />
      
      <!-- Choose Program/Degree -->
     <select class="selectpicker" id="year-menu" data-style="btn-primary" title='Choose Year'>
         <option data-hidden="true"></option>
	 <option value="2010">2010</option>
	 <option value="2011">2011</option>
         <option value="2012">2012</option>
         <option value="2013">2013</option>
         <option value="2014">2014</option>
     </select>
     <br />
     <br />
   



<a class="btn btn-primary btn-md" href=""><?php echo
	    $this->translate ('Back to Main') ?> </a>
	  <!-- Get Button trigger modal -->
<a class="btn btn-primary btn-md" id="submit">
  Submit
</a><p></p>
                    </div><!--close container-->
                </div><!--close column-->
		
		<!--column 2-->
		<div id="content">
		</div>
	</div>
	                    
    </body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
<script src="../js/bootstrap-rta.min.js"></script>
<script src="../js/bootstrap-select.js"></script>

<script>

// Submit data to get plans
$(document).on('click', '#submit', function () {
    var action = document.getElementById('action-menu').value;
    var unit = document.getElementById('unit-menu').value;
    var program = $( "#prog-menu option:selected" ).val();
    var year = document.getElementById('year-menu').value;
    alert(program);
   // asynchronous ajax code to get plans
   $.ajax({
      url: 'http://localhost/zendframework/reports/viewPlans/31/2007',
      type: "GET",
      dataType: "text",
      error : function(xhr, status, error) {
        alert(error);
      },
      success: function(html){
        document.getElementById('content').innerHTML = html;
      },
   });
});
</script>
<script>

// load actions based on user privileges
$(document).ready(function() {
   var actions = <?php print json_encode($useractions); ?>;
   for (var i = 0; i < actions.length; i++){
      $('#action-menu').append('<option>' + actions[i] + '</option>');
   }
   // call code to initialize the selectpicker
   // this must come after the options are initialized
   $('.selectpicker').selectpicker();
});

// update unit/department options based on actions
$(document).on('change', '#action-menu', function () {
   $action = $('#action-menu option:selected').val();
   // clear selectorlist before adding unit/department options
   var oldSelections = $('#unit-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   // data-hidden="true" shows title on button
   $('#unit-menu').append('<option  data-hidden="true"></option>');
   $('#unit-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('default', array(
                                    'controller'=>'reports',
                                    'action'=>'getUnits')); ?>";

   urlform = urlform + '/' + $action;
   // asynchronous ajax code to populate unit/department selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(unitsJson){
         for (var i = 0; i < unitsJson.length; i++){
            $('#unit-menu').append('<option>' + unitsJson[i].id + '</option>');
         }
         $('#unit-menu').selectpicker('refresh');
      },
   });
});

// update program options based on unit/department
$(document).on('change', '#unit-menu', function () {
   $unit = $('#unit-menu option:selected').val();
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('default', array(
                                    'controller'=>'reports',
                                    'action'=>'getPrograms')); ?>";
   urlform = urlform + '/' + $unit;
   // asynchronous ajax code to populate program/degree selector
   // build stuff here and make it work
    var stuff = {};
    //key programs, value = array of programs
   $.ajax({
      url: urlform,
      type: "GET", //post
      dataType: "json",//data 
      data:stuff,
      // content type
      
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
		 
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
});
</script>
                     
                            
                            
                            
                            
 










