<?php
// modifyreport.phtml:

$title = 'Modify Report';
$this->headTitle($title);
?>
<html>
    <body>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="../../css/bootstrap.min.css"> 
    <link rel="stylesheet" href="../../css/bootstrap-rta.min.css">
    <style>
        textarea {
            width: 300px;
        }</style>
        <div class="container">
           	<center><h3>Assessment Reports</h3>
            
	    </center>
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
                       
	<p></p>
                         <!-- Choose Action -->
      <select class="selectpicker" id="action-menu" data-style="btn-primary" title='Choose Action'>
         <option data-hidden="true"></option>
         <option>View</option>
         <option>Add</option>
         <option>Modify</option>
      </select>  
     <br />
     <br />
      <!-- Choose Department/Unit -->
      <select class="selectpicker" id="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
         <option data-hidden="true"></option>
      </select>  
     <br />
     <br />
   
   <!--
      <h6>Enter Department Name</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" id='unit-menu2' >
         </ul>
      </div>
      <input type="text" id="unit-input" class="form-control" placeholder="Department">
      </div>
   -->
      <!-- Choose Program/Degree -->
      <select class="selectpicker" id="prog-menu" data-style="btn-primary" title='Choose Program/Degree' multiple>
         <option data-hidden="true"></option>
      </select>
     <br />
     <br />
   
	  <!-- Get Button trigger modal -->
<a class="btn btn-primary btn-md" href="../view-All-Reports">
  Find Reports &raquo;
</a>

<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>
                    </div><!--close container-->
                </div><!--close column-->
		
		<!--column 2-->
		<p></p>
		<div class="col-md-8">
		   <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <colgroup>
        <col class="col-xs-8">

      </colgroup>
     
  <div class="bs-example">
    <?php
    $form->setAttribute('action', $this->url('reports', array('action' => 'updateReport')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id')->setAttribute('value', $report[0]['id']));
    ?>
    <table class="table">
      
          <h6>View Report</h6>
       <h4>TBD</h4>
      
    
    <div class="controls">
	<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
           1. Outcomes
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
	<div>
	<?php $ctr = 0;?>

	<?php foreach($outcomes as $outcome) : ?>
	    <?php $ctr++;?>
	     <?php echo($ctr); ?>.<?php echo $outcome;?>
	    </br>
	    
	    <?php endforeach; ?>
	</div>
      </div>
    </div>
  </div>
  </br>
  </div><!-- /.col-lg-6 -->      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
           2. Describe assessment method.
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
<textarea readonly rows="10" cols="60" class="textbox" id="" name=""
		  ><?php echo $report[0]['assessment_method']?></textarea>      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
           2. Describe population assessed.
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
		  <?php echo $this->formRow($form->get('population')->setAttribute('value', $report[0]['population']))?>      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
           3. Describe results.
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
		  <?php echo $this->formRow($form->get('results')->setAttribute('value', $report[0]['results']))?>      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
           3. Describe conclusion.
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      <div class="panel-body">
<?php echo $this->formRow($form->get('conclusions')->setAttribute('value', $report[0]['conclusions']))?>     </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
           5. Describe actions.
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse">
      <div class="panel-body">
<?php echo $this->formRow($form->get('actions')->setAttribute('value', $report[0]['actions']))?>    </div>
    </div>
  </div>
  
</div>
<a href="#">AttachedFile.pdf</a><P></P>
	
        </div> <!-- controls -->
	<?php echo $this->formRow($form->get('submit'))?>


      <tbody>
       
      </tbody>
    </table></table>
    <?php echo $this->form()->closeTag();?>

  </div><!-- /example -->
   
                   
    </div>
         
    </body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../../js/bootstrap.min.js"></script>
<script src="../../js/bootstrap-rta.min.js"></script>
<script src="../../js/bootstrap-select.js"></script>
<script>

// call loadDepts on page load
$(document).ready(function() {
   $.rta(); // load rta features - simplest implementation
   loadUnits();
});

// function to create department/unit options
function loadUnits(){
   
   // convert php array into javascript array
   var units = <?php print json_encode($units); ?>;
   // assign unit ids to html dropdown
   for (var i = 0; i < units.length; i++){
      //$('#unit-menu2').append('<li><a>' + units[i].id + '</a></li>');
      $('#unit-menu').append('<option>' + units[i].id + '</option>');
   }
   // call code to initialize the selectpicker
   // this must come after the options are ini
   $('.selectpicker').selectpicker();
   
}

// call loadPrograms when user chooses a department/unit
$(document).on('change', '#unit-menu', function () {
    loadPrograms($('#unit-menu option:selected').val());
});

// function to create program options based on department/unit chosen
function loadPrograms($unit){
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('review', array(
                                    'controller'=>'review',
                                    'action'=>'get')); ?>";
   urlform = urlform + '/' + $unit;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
}
</script>
