<!DOCTYPE html>

<html>
<head>
<title>Page Title</title>
	    <link rel="stylesheet" href="../css/bootstrap-select.css">

</head>

<body>

    <select class="selectpicker">
	<option>Mustard</option>
	<option>Ketchup</option>
	<option>Relish</option>
      </select>
    
    <div class="btn-group">
  <button type="button" class="btn btn-default">Left</button>
  <button type="button" class="btn btn-default">Middle</button>
  <button type="button" class="btn btn-default">Right</button>
</div>
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select</button>


</body>
<script>
$('.selectpicker').selectpicker({
      style: 'btn-info',
      size: 4
  });
</script>
</html>

