<?php

// If there aren't results, tell user
if(!$results){
    echo '</br></br></br></br>There are no plans that match your criteria';
}else{

?>

<div class="col-md-6">

    <div class="panel-group" id="accordion">
	<!-- Loop through returned plans -->
	<?php
	    $ctr = 0;
	    foreach($plans as $plan) :

	    $ctr++; 
	    $colId = 'collapse' . $ctr;
	    $colNum = '#' . $colId;
	?>
	    
	<div class="panel panel-success">
	    <div class="panel-heading">
		<h4 class="title">
		    <a data-toggle="collapse" data-parent="#accordion" href="<?php echo $colNum; ?>">Plan <?php echo $ctr; ?> </a>
		    <!-- add ".custom {width: 70px !important;}" to the bootstrap.css file and add 'custom' and 'pull-right' to btn-->
		    <input class="btn btn-primary btn-md pull-right btn custom" onclick="getReports('<?php echo $action;?>', <?php echo $plan->id; ?>);" id="<?php echo $action;?>" value="<?php echo $action;?>"></input>
		    
		</h4>
	    </div><!-- close heading -->
	    <div id="<?php echo $colId; ?>" class="panel-collapse collapse">
		<div class="panel-body">
		    <table class="table">
			<?php
			    $oCtr = 0; 
			    foreach($plan->descriptions as $text) : 
			    $oCtr++;
			?>
			<tr>
			    <th> <?php echo($oCtr); ?>.</th>
			    <td><?php echo $text;?></td>
			</tr>
			<?php endforeach; ?>
		    </table>
			
		</div><!-- close body-->
	    </div><!-- close id-->
	</div><!-- close panel-success-->

	<?php
	    endforeach;}
	?>

    </div><!-- close panel-group-->
</div><!-- close column-->