<?php

if(!$results){
    echo 'There are no reports associated with this plan';
}else{

?>
<div class="col-md-8">
    <div class="table-responsive">
	<table class="table table-bordered table-striped">
	    <colgroup>
		<col class="col-xs-8">
	    </colgroup>  
	    <div class="bs-example">
		<table class="table">
		    <h6>View Report</h6>
		    <h4><?php echo $report[0]['unit_id'] . ' - ' . $report[0]['name'] . ' - ' . $report[0]['year'];?></h4>
		    <div class="controls">
			<div class="panel-group" id="accordion">
			    
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<?php
					if($report[0]['meta_flag'] == 0){
					    $type = 'Outcomes';
					}else{
					    $type = 'Meta Description';
					}
					
					?>
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><?php echo $type;?></a>
				    </h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse">
				    <div class="panel-body">
				    
					<?php
					$ctr = 0;
					foreach($descriptions as $description) : 
					    $ctr++;
					    echo($ctr); ?>.<?php echo $description;
					endforeach;
					?>
				   
				</div>
			    </div>
				
			
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Population Assessed</a>
				    </h4>
				</div>
				<div id="collapseTwo" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['population']?>
				    </div>
				</div>
			    </div>
		
		
		
		
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					 <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Results</a>
				    </h4>
				</div>
				<div id="collapseThree" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['results']?>
				    </div>
				 </div>
			    </div>
		
		
		
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">Conclusion</a>
				    </h4>
				</div>
				<div id="collapseFour" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['conclusions']?>
				    </div>
				</div>
			    </div>
			    
			    
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">Actions</a>
				    </h4>
				</div>
				<div id="collapseFive" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['actions']?>
				    </div>
				</div>
			    </div>
			</div>
	    <a href="#">AttachedFile.pdf</a><P></P>
	</div> <!-- controls -->
        <button type="button" class="btn btn-primary">Back to Reports</button>&nbsp;
	<button type="button" class="btn btn-primary">Print</button>&nbsp;
    </table>
</table>
<?php
 
}
?>


