<?php

if(!$results){
    echo '</br></br></br></br>There are no plans that match your criteria';
}else{

?>

<div class="col-md-6">
    <div class="input-group">
	<div class="panel-group" id="accordion">
	    <!-- Start Plan here -->
	    <?php
		$ctr = 0;
		foreach($plans as $plan) :
		$ctr++; 
		$colId = 'collpase' . $ctr;
		$colNum = '#' . $colId;
	    ?>
	    
	    <div class="panel panel-success">
		<div class="panel-heading">
		    <h4 class="title">
			<a data-toggle="collapse" data-parent="#accordion" href="<?php echo $colNum; ?>">Plan <?php echo $ctr; ?></a>
			<input class="btn btn-primary btn-md" onclick="getReports('<?php echo $action;?>', <?php echo $plan->id; ?>);" id="<?php echo $action;?>" value="<?php echo $action;?>"></input>
		    </h4>
		</div>
		<div id="<?php echo $colId; ?>" class="panel-collapse collapse">
		    <div class="panel-body">
			<div class="control-group">
			    <div class="controls">
				<table class="table">
				    <?php
					$oCtr = 0; 
					foreach($plan->descriptions as $text) : 
					$oCtr++;
				    ?>
				    <tr>
					<th> <?php echo($oCtr); ?>.</th>
					<td><?php echo $text;?></td>
				    </tr>
				    <?php endforeach; ?>
				</table>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	    <?php
		endforeach;
	    ?>
	    
	</div>
    </div>
<?php
 
}
?>