<?php

if(!$results){
    echo 'There are no reports associated with this plan';
}else{
?>
<div class="col-md-8">
    <div class="table-responsive">
	<table class="table table-bordered table-striped">
	    <colgroup>
		<col class="col-xs-8">
	    </colgroup>  
	    <div class="bs-example">
		<table class="table">
		    <h6>View Report</h6>
		    <h4><?php echo $report[0]['unit_id'] . ' - ' . $report[0]['name'] . ' - ' . $report[0]['year'];?></h4>
		    <div class="controls">
			<div class="panel-group" id="accordion">
			    
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<?php
					if($report[0]['meta_flag'] == 0){
					    $type = 'Outcomes';
					}else{
					    $type = 'Meta Description';
					}
					
					?>
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><?php echo $type;?></a>
				    </h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse">
				    <div class="panel-body">
				    
					<?php
					$ctr = 0;
					foreach($descriptions as $description) : 
					    $ctr++;
					    echo($ctr); ?>.<?php echo $description . '</br>';
					endforeach;
					?>
				   
				    </div>
				</div>
			    </div>
			
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Population Assessed</a>
				    </h4>
				</div>
				<div id="collapseTwo" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['population']?>
				    </div>
				</div>
			    </div>
		
		
		
		
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					 <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Results</a>
				    </h4>
				</div>
				<div id="collapseThree" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['results']?>
				    </div>
				 </div>
			    </div>
		
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">Conclusion</a>
				    </h4>
				</div>
				<div id="collapseFour" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['conclusions']?>
				    </div>
				</div>
			    </div>
			    
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">Actions</a>
				    </h4>
				</div>
				<div id="collapseFive" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['actions']?>
				    </div>
				</div>
			    </div>
			    
			    <div class="panel panel-default">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<?php
					    if($report[0]['feedback'] == 2){
						$feedback = 'Final Version';
					    }else{
						$feedback = 'In need of revision';
					    }
					?>
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">Feedback - <?php echo $feedback; ?></a>
				    </h4>
				</div>
				<div id="collapseSix" class="panel-collapse collapse">
				    <div class="panel-body">
					    <?php echo $report[0]['feedback_text']?>
				    </div>
				</div>
			    </div>
			</div>
			    <table>
				<th>File</th><th>&nbsp&nbspDescription</th>
				<?php
				    if(count($documents) > 0){
					foreach($documents as $doc){
				?>
				<tr><td><a href="<?php echo $this->url('id',
					array('action'=>'download',
				       'id' => $doc['id'],
				       ));
					?>"><?php echo $doc['file_name']; ?></a></td><td>
					<?php echo '&nbsp&nbsp' . $doc['file_description']; ?>
					</td></tr>
					<?php
					}
				    }
				?>
			    </table>
	    </br>
	</div> <!-- controls -->
	<button type="button" class="btn btn-primary" style="width:100px" onclick="window.print();">Print</button>&nbsp;
    </table>
</table>
<?php
 
}
?>


