<?php
// module/Mock/view/mock/mock/add.phtml:

$title = 'Add New Assessment Reportasdfasdf';
$this->headTitle($title);
?>	
<html>
    <body>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="../css/bootstrap.min.css"> 
    <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
    <style>
        textarea {
            width: 300px;
        }</style>
	<div class="container"></div>
		

	
	
	
	
	<center><h3>Assessment Reports</h3>
            
	    </center>
	    
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
                       
	<p></p>
                        <h6>Department Name</h6>
                       
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science</a></li>
                                    <li><a href="#">Science</a></li>
                                    <li><a href="#">Math</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Prog/Degree dropdown -->
                        <h6>Degree/Program</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="MS/Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    
				    <li><a href="#">BS/Computer Science</a></li>
                                    <li><a href="#">MS/Computer Science</a></li>
                                    <li><a href="#">MA/Computer Science</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year --> <h6>Academic Year</h6>
			<div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="2014-15">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">

                                    <span data-bind="label">Select</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>
                            </div>			    
                        </div><p></p>
			
	  <!-- Get Button trigger modal -->
<a class="btn btn-primary btn-md" href="./reports/viewAllReports">
  View Reports &raquo;
</a>
<a class="btn btn-primary btn-md btn" href="./addReport">
  Add New &raquo;
</a>
<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>
                    </div><!--close container-->
                </div><!--close column-->
		
		<!--column 2-->
		<p></p>
                    <div class="col-md-6">
			   
			    <div class="input-group">
     
                        <div class="panel-group" id="accordion">
			   
					<div class="panel panel-success">
				    <div class="panel-heading">
					<h4 class="title">
					    <a data-toggle="collapse" data-parent="#accordion"
					       href="#collapseTwo">Plan #1 with Corresponding Student Outcomes</a>
					
					<a class="btn btn-primary btn-xs" href="./viewReport/369"><?php echo
	    $this->translate ('View') ?> &raquo;</a>&nbsp;<a class="btn btn-primary btn-xs" href="./modifyReport/369"><?php echo
	    $this->translate ('Modify') ?> &raquo;</a>
					</h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
					    <div class="control-group">
						<div class="controls">
						    <table class="table">
	<tr>
	  <th> 1.</th> <td>Students should understand a portion of the standard undergraduate mathematics curriculum, including the theoretical concepts which form the foundations of integral and differential calculus, differential equations, and elementary linear algebra.</td>
	</tr> <tr class="active">
	  <td> 2.</td> <td>Students should be able to apply formulas and procedures learned in their courses in an appropriate fashion and make decisions based upon their solutions.</td>
	</tr>
    </table></div>
					    </div>
					</div>
				    </div>
				<div class="panel panel-success">
				    <div class="panel-heading">
					<h4 class="title">
					    <a data-toggle="collapse" data-parent="#accordion"
					       href="#collapseTwo">Plan #2 with Corresponding Student Outcomes</a>
					
					<a class="btn btn-primary btn-xs" href="./viewReport/370"><?php echo
	    $this->translate ('View') ?> &raquo;</a><a class="btn btn-primary btn-xs" href="./modifyReport/370"><?php echo
	    $this->translate ('Modify') ?> &raquo;</a>
					</h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
					    <div class="control-group">
						<div class="controls">
						    <table class="table">
	<tr>
	  <th> 1.</th> <td>Students should understand a portion of the standard undergraduate mathematics curriculum, including the theoretical concepts which form the foundations of integral and differential calculus, differential equations, and elementary linear algebra.</td>
	</tr> <tr class="active">
	  <td> 2.</td> <td>Students should be able to apply formulas and procedures learned in their courses in an appropriate fashion and make decisions based upon their solutions.</td>
	</tr>
    </table></div>
					    </div>
					</div>
				    </div>
				    <div class="panel panel-success">
					<div class="panel-heading">
					    <h4 class="title">
						<a data-toggle="collapse" data-parent="#accordion"
						   href="#collapseThree">Plan #3 with Corresponding Student Outcomes</a>
					    <a class="btn btn-primary btn-xs" href="./viewReport/462"><?php echo
	    $this->translate ('View') ?> &raquo;</a><a class="btn btn-primary btn-xs" href="./modifyReport/462"><?php echo
	    $this->translate ('Modify') ?> &raquo;</a>
					    </h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse">
					    <div class="panel-body">
						<div class="control-group">
						    <div class="controls">
							 <table class="table">
	<tr>
	  <th> 1.</th> <td>Students should understand a portion of the standard undergraduate mathematics curriculum, including the theoretical concepts which form the foundations of integral and differential calculus, differential equations, and elementary linear algebra.</td>
	</tr> <tr class="active">
	  <td> 2.</td> <td>Students should be able to apply formulas and procedures learned in their courses in an appropriate fashion and make decisions based upon their solutions.</td>
	</tr>
    </table> </div></div></div>
<a class="btn btn-primary btn-md" href="../img/userguide.pdf"><?php echo $this->translate
            ('Preview Report') ?> &raquo;</a>			<button type="submit" class="btn btn-primary">Submit Report</button>
		    </div>
	    </div>	</div></div></div>
						
				
			</div>
					    </div>
				</div>
			    </div>
	</div>
	 <script src="../js/bootstrap.min.js"></script>
                        <script src="../js/jquery.min.js"></script>
                        <script src="../js/bootstrap3-typeahead.js"></script>
                        <script src="https://code.jquery.com/jquery.js"></script>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script src="../js/bootstrap-rta.min.js"></script>
                        <script>
                            $(document).ready(function() {
                                document.getElementById('ta_sample').value = "";
                                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
                            });
                        </script>
    </body>
</html>









