
		<div class="col-md-6">
		    <div class="input-group">
			<div class="panel-group" id="accordion">
			    <!-- Start Plan here -->
			    <?php
			    $ctr = 0; ?>
			    <?php foreach($plans as $plan) : ?>
			    <?php $ctr++; 
			    $form = $plan->form;
			    $form->setAttribute('action', $this->url('reports', array('action' => 'modifyReport')));
			    $form->prepare();
			    echo $this->form()->openTag($form);
			    echo $this->formHidden($form->get('id')->setAttribute('value', $plan->id));
			    ?>
				<div class="panel panel-success">
				    <div class="panel-heading">
					<h4 class="title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Plan <?php echo($ctr) ?></a>
				     
					    <?php echo $this->formSubmit($form->get('submit')); ?>
					    
					</h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
					    <div class="control-group">
						<div class="controls">
						    <table class="table">
							<?php $oCtr = 0; ?>
							<?php foreach($plan->outcomes as $outcome) : ?>
							<?php $oCtr++;
							?>
							<tr>
							    <th> <?php echo($oCtr); ?>.</th>
							    <td><?php echo $this->formRow($form->get('outcome')->setAttribute('value', $outcome));?></td>
							</tr>
							
							
							<?php endforeach; ?>
						    </table>
						</div>
					    </div>
					</div>
				    </div>
				</div>
			    <?php echo $this->form()->closeTag();?>
			    <?php endforeach; ?>
			    <!-- End Plan here -->










