<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Assessment System'), '<span class="zf-green">', '</span>') ?></h1>
</div>


<div class="row">
    

        <div class="btn-group btn-group-justified">
        
        <a href="<?php echo $this->url('application', array('action'=>'index'));?>"
        class="btn btn-primary" role="button">Back to home</a>    
    
            
        </div>
