
<?php

   $title = 'Review Assessment Plans and Reports';
    $this->headTitle($title);
?>      
<center><h3>Review Assessment Plans or Reports</h3>
<div class="row">
   <div class="col-md-4">
   <div class="container">
   
      <!-- Dept typeahead -->
      <h6>Enter Department Name</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" id="unit-menu">
         </ul>
      </div>
      <input type="text" id="unit-input" class="form-control" placeholder="Department">
      </div><!-- /input-group -->
   
      <!-- Prog/Degree dropdown -->
      <h6>Select Program/Degree</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" id="prog-menu">
         </ul>
      </div>
      <input type="text" id="prog-input" class="form-control" placeholder="Program/Degree">
      </div><!-- /input-group -->
   
      <!-- Prog/Degree dropdown -->
      <h6>Select Program/Degree</h6>
        <select class="selectpicker" data-style="btn-primary" multiple>
         <option>stuff</option>
         <option>thisstuff</option>
        </select>
        
      </div>
   
   <!-- Year  -->
      <h6>Select Academic year</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">2014-15
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" >
        
         </ul>
      </div>
      <input type="text" class="form-control" placeholder="Year">
      </div><!-- /input-group -->
   
      <p></p>
      <a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
      ('Find Plan') ?> &raquo;</a>
      </div><!--close container-->
</div><!--close column-->

<!--column 2-->
<p>This is where the plan or report will pop up with a feedback box.</p>
<style>
   textarea {
      width: 400px;
   }
</style>
<div class="container">
   <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
      <div class="control-group">
      <label class="control-label" for="ta_sample">Feedback Response</label>
      <div class="controls">
         <textarea rows="8" cols="60" class="rta" id="ta_sample" name="ta_sample"></textarea>
      </div> <!-- controls -->
      </div> <!-- control-group -->
   </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-rta.min.js"></script>
<script>

// on page load
$(document).ready(function() {
 //   $('.selectpicker').selectpicker();
   $.rta(); // load rta features - simplest implementation
   loadUnits();
});

// populate units
$(document).on('click', '#unit-menu li a', function () {
   $('#unit-input').val($(this).text());
   loadPrograms($(this).text());
});

// function to create unit options
function loadUnits(){
    
   // convert php array into javascript array
   var units = <?php print json_encode($units); ?>;
   // assign unit ids to html dropdown
   for (var i = 0; i < units.length; i++){
      $('#unit-menu').append('<li><a>' + units[i].id + '</a></li>');
   }
   //$('unit-menu').listview('refresh');
}

function loadPrograms($unit){
   // asynchronous ajax code to populate program
   // do we need to return the redirect?
   var urlform = "<?php echo $this->url('review', array(
                                    'controller'=>'review',
                                    'action'=>'get')); ?>";
                            
   urlform = urlform + '/' + $unit;
   alert(urlform);
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<li><a>' + programsJson[i].name + '</a></li>');
         }
      },
   });
   
}
</script>

