
<?php

   $title = 'Review Assessment Plans and Reports';
   $this->headTitle($title);
?>      
<center><h3>Review Assessment Plans or Reports</h3>
<div class="row">
   <div class="col-md-4">
   <div class="container">
   
     <br />
     <br />
      <!-- Choose Action -->
      <select class="selectpicker" id="action-menu" data-style="btn-primary" title='Choose Action'>
         <option data-hidden="true"></option>
         <option>View</option>
         <option>Add</option>
         <option>Modify</option>
      </select>  
     <br />
     <br />
      <!-- Choose Department/Unit -->
      <select class="selectpicker" id="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
         <option data-hidden="true"></option>
      </select>  
     <br />
     <br />
   
   <!--
      <h6>Enter Department Name</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" id='unit-menu2' >
         </ul>
      </div>
      <input type="text" id="unit-input" class="form-control" placeholder="Department">
      </div>
   -->
      <!-- Choose Program/Degree -->
      <select class="selectpicker" id="prog-menu" data-style="btn-primary" title='Choose Program/Degree' multiple>
         <option data-hidden="true"></option>
      </select>
     <br />
     <br />
   
     
      <p></p>
      <a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
      ('Find Plan') ?> &raquo;</a>
      </div><!--close container-->
</div><!--close column-->

<!--column 2-->
<p>This is where the plan or report will pop up with a feedback box.</p>
<style>
   textarea {
      width: 400px;
   }
</style>
<div class="container">
   <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
      <div class="control-group">
      <label class="control-label" for="ta_sample">Feedback Response</label>
      <div class="controls">
         <textarea rows="8" cols="60" class="rta" id="ta_sample" name="ta_sample"></textarea>
      </div> <!-- controls -->
      </div> <!-- control-group -->
   </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-rta.min.js"></script>
<script src="js/bootstrap-select.js"></script>


