<?php
    $title = 'Review Assessment Plans and Reports';
    $this->headTitle($title);
?>      
<center><h3>Review Assessment Plans or Reports</h3>
<div class="row">
   <div class="col-md-4">
   <div class="container">
   
      <!-- Dept typeahead -->
      <h6>Enter Department Name</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" id="unit-menu">
         </ul>
      </div>
      <input type="text" class="form-control" placeholder="Department">
      </div><!-- /input-group -->
   
      <!-- Prog/Degree dropdown -->
      <h6>Select Program/Degree</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Select
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu">
         </ul>
      </div>
      <input type="text" class="form-control" placeholder="Program/Degree">
      </div><!-- /input-group -->
   
      <!-- Year  -->
      <h6>Select Academic year</h6>
      <div class="input-group">
      <div class="input-group-btn">
         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">2014-15
         <span class="caret"></span>
         </button>
         <ul class="dropdown-menu" >
        
         </ul>
      </div>
      <input type="text" class="form-control" placeholder="Year">
      </div><!-- /input-group -->
   
      <p></p>
      <a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
      ('Find Plan') ?> &raquo;</a>
      </div><!--close container-->
</div><!--close column-->

<!--column 2-->
<p>This is where the plan or report will pop up with a feedback box.</p>
<style>
   textarea {
      width: 400px;
   }
</style>
<div class="container">
   <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
      <div class="control-group">
      <label class="control-label" for="ta_sample">Feedback Response</label>
      <div class="controls">
         <textarea rows="8" cols="60" class="rta" id="ta_sample" name="ta_sample"></textarea>
      </div> <!-- controls -->
      </div> <!-- control-group -->
   </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-rta.min.js"></script>
<script>
$(document).ready(function() {
   loadUnits();
   $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
});
function loadUnits(){
    <?php
       // iterate over database results forming a php array
       foreach ($units as $unit) : 
           $unitarray[] = $unit;
       endforeach;
   ?>
   // convert php array into javascript array
   var units = <?php print json_encode($unitarray); ?>;
   // assign unit ids to html dropdown
   //$('ul').append('<li><a>hello</a></li>').listview('refresh');
  // for (var i = 0; i < units.length; i++){
      // $("#unit-menu").append('<li>' + units[0].id + '</li>');
      $('ul').append('<li>' + units[1].id + '</li>');
   }
   //$('unit-menu').listview('refresh');
   
}
</script>

