<?php
//add.phtml:

$title = 'Add New Student Outcome';
$this->headTitle($title);
?>
<html>
    <body>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../css/bootstrap.min.css">
        <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
        <style>
            textarea {
                width: 300px;
            }
        </style><a class="btn btn-primary btn-md" href="./so">&laquo;<?php
            echo
            $this->translate('Back to Student Outcomes Home')
            ?> </a> <p></p>
        <div class="container">
            <center><h3>Add New Student Outcome</h3>
                <p><h6>Instructions for use...</h6></p></center>
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead -->
                    <div class="container">
                        <div class="input-group" >
                            <p></p>
                        </div><!-- /input-group -->
                        <h6>Enter Department Name</h6>
                        <div class="input-group">
                            <input id="dept_search" type="text" data-provide="typeahead" class="form-control"
                                   data-source='["CSC", "MTH", "ENG", "ART", "BIO"]'>
                            <div class="input-group-btn">
                                <button class="btn btn-primary"
                                        type="button">Clear</button>
                            </div>
                        </div><!-- /input-group -->
                        <!-- Prog/Degree dropdown -->
                        <h6>Select Program/Degree</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Prog/Deg appears here">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Pr/Dg
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science/BS</a></li>
                                    <li><a href="#">Computer Science/MS</a></li>
                                    <li><a href="#">Computer Science/BS</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year -->
                        <h6>Select Academic year</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Year appears here">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">
                                    <span data-bind="label">Year</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>
                            </div>
                        </div>
                        <p></p>
                        <a class="btn btn-primary btn-lg" href="#"><?php
                            echo $this->translate
                                    ('Start New Student Outcome')
                            ?> &raquo;</a>
                        <div class="control-group">
                            <div class="controls">
                                <h4>Upload Prepared Student Outcome File:</h4>
                                <input class="input-file" id="fileInput" type="file">
                                <button type="submit" class="btn btn-primary btn-xs">Upload</button>
                                <button type="submit" class="btn btn-warning btn-xs">Cancel</button>
                            </div>
                        </div>
                    </div><!--close container-->
                </div><!--close column-->
                <!--column 2-->
                <p></p>
                <div class="col-md-6">
                    <p><h6>Enter answers below:</h6></p>
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion"
                                       href="#collapseOne">Question #1</a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <div class="control-group">
                                        <div class="controls">
                                            <label class="control-label" for="ta_sample">Type in answers below</label>
                                            <div class="controls">
                                                <textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Sample TextArea"></textarea>
                                            </div> <!-- controls -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion"
                                       href="#collapseTwo">Question #2</a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
                                        <div class="control-group">
                                            <label class="control-label" for="ta_sample">Type in answers below</label>
                                            <div class="controls">
                                                <textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Sample TextArea"></textarea>
                                            </div> <!-- controls -->
                                        </div>
                                </div>
                                <div class="panel panel-success">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion"
                                               href="#collapseThree">Question #3</a>
                                        </h4>
                                    </div>
                                    <div id="collapseThree" class="panel-collapse collapse">
                                        <div class="panel-body">

                                            <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
                                                <div class="control-group">
                                                    <label class="control-label" for="ta_sample">Type in answers below</label>
                                                    <div class="controls">
                                                        <textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Sample TextArea"></textarea>
                                                    </div> <!-- controls -->
                                                </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-primary btn-md" href="../img/userguide.pdf"><?php
                            echo $this->translate
                                    ('Preview SO')
                            ?> &raquo;</a>
                        <button type="submit" class="btn btn-primary">Submit SO</button>
                        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                        <script src="../js/jquery.min.js"></script>
                        <script src="../js/bootstrap3-typeahead.js"></script>
                        <script src="https://code.jquery.com/jquery.js"></script>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script src="../js/bootstrap.min.js"></script>
                        <script src="../js/bootstrap-rta.min.js"></script>
                        <script>
                            $(document).ready(function() {
                                document.getElementById('ta_sample').value = "";
                                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>