<?php
// module/Student/view/mock/mock/index.phtml:

$title = 'Mock-up Login';
$this->headTitle($title);
?>
<p></p>
<html><body>
    <div class="container">
        <center><h3>NCC Assessment Portal Login</h3>
          
          <div class="container">
<div class="jumbotron">
       <form action='../mock' method="post" accept-charset="UTF-8">
  <input id="user_username" style="margin-bottom: 15px;" type="text" name="user[username]" size="30" />
  <p></p>
  <input id="user_password" style="margin-bottom: 15px;" type="password" name="user[password]" size="30" />
  <p></p>
  <a href="#">Forgot Password?</a>
  <p></p>
  <input class="btn btn-primary" type="submit" name="commit" value="Login" />
</form>
</div>
    </div> <!-- /container -->
      
    </div>
     </center>
</html>