<textarea id="outcomeTextArea" rows="6" cols="90" placeholder=""></textarea>
<br />
<br />
<button class="btn btn-primary btn-lg" id="back">Back to Outcomes</button>
<button class="btn btn-primary btn-lg" id="add-button" value="Add">Add</button>
<br />
<br />

<script>
     $(document).ready(function(){
 
     var program = <?php echo $this->escapeHtml($programChosen);?>;
   
     //  handle add button click
     $("#add-button").click(function (){

	  var text = $('#outcomeTextArea').val();
     
	  // create url for redirect
	  var urlform = "<?php echo $this->url('outcomes', array(
                                    'controller'=>'outcomes',
                                    'action'=>'getOutcomes')); ?>";
	  urlform = urlform + '/' + program;
      
	  // asynchronous ajax code to populate program/degree selector
	  $.ajax({
	       url: urlform,
	       type: "POST",
	       data: { action: "add", pid: program, outcomeText: text  }, 
	       dataType: "text",
	       error : function(xhr, status, error) {
	       console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
	       },
	       success: function(partialHtml){
		    // clear any existing html in the partial div
		    $('#partialHolder').html(partialHtml);
	       },
	  });
     });

     //  handle back button click
     $("#back").click(function (){
  
	  // create url for redirect
	  var urlform = "<?php echo $this->url('outcomes', array(
                                    'controller'=>'outcomes',
                                    'action'=>'getOutcomes')); ?>";
	  urlform = urlform + '/' + program;
      
	  // asynchronous ajax code to populate program/degree selector
	  $.ajax({
	       url: urlform,
	       type: "GET",
	       dataType: "text",
	       error : function(xhr, status, error) {
	       console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
	       },
	       success: function(partialHtml){
		    // clear any existing html in the partial div
		    $('#partialHolder').html(partialHtml);
	       },
	  });
     });
});
</script>