<?php // partial.phtml ?>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
      
    <tr>
    <th>Outcome ID</th>
    <th>Program ID</th>
    <th>Description</th>
    <th>Active</th>
    <th>Action</th>
</tr>
<?php foreach ($outcomes as $outcome) : ?>
<tr>
    <td><?php echo $this->escapeHtml($outcome['id']);?></td>
    <td><?php echo $this->escapeHtml($outcome['program_id']);?></td>
    <td><?php echo $this->escapeHtml($outcome['outcome_text']);?></td>
    <td><?php echo $this->escapeHtml($outcome['active_flag']);?></td>
    <td>


  <div class="btn-group-vertical">
        <button class="btn btn-primary" type="button">Edit</button>
        <button class="btn btn-primary" type="button">Delete</button>
  </div>

    </td>
</tr>
<?php endforeach; ?>
    
    
    </table>
       
                   
    </div> <!-- Table reponsive div close-->