<?php
// module/Mock/view/mock/mock/add.phtml:

$title = 'Add New Assessment Plan';
$this->headTitle($title);
?>	
<html>
    <body> </style><a class="btn btn-primary btn-md" href="./plans">&laquo;<?php echo
	    $this->translate ('Back to Plans Home') ?> </a> <p></p>
	<div class="container">
	<center><h3>Add New Assessment Plan</h3>
            <p><h6>Instructions for use...</h6></p></center>
            <div class="row">
		<div class="col-md-4">
                    <!-- Dept typeahead -->
		    <div class="container">
			<div class="input-group" >
			    <p></p>
			</div><!-- /input-group -->
			<h6>Enter Department Name</h6>
                        <div class="input-group">
                            <input id="dept_search" type="text" data-provide="typeahead" class="form-control"
                    data-source='["CSC", "MTH", "ENG", "ART", "BIO"]'>
			<div class="input-group-btn">
				    <button class="btn btn-primary"
				    type="button">Clear</button>
                        </div>
			</div><!-- /input-group -->
			<!-- Prog/Degree dropdown -->
                        <h6>Select Program/Degree</h6>
                        <div class="input-group">			   
                            <input type="text" class="form-control"
			    placeholder="Prog/Deg appears here">
                                 <div class="input-group-btn">
				<button type="button" class="btn btn-primary
				dropdown-toggle"
					data-toggle="dropdown">Pr/Dg
				    <span class="caret"></span>
				</button> <ul class="dropdown-menu">
				    <li><a href="#">Computer Science/BS</a></li>
				    <li><a href="#">Computer Science/MS</a></li>
				    <li><a href="#">Computer Science/BS</a></li>
				</ul>
			    </div>
			</div>
			<!-- Year --> <h6>Select Academic year</h6> <div
			class="input-group">
			    <input type="text" class="form-control"
			    placeholder="Year appears here">
                                <div class="input-group-btn">
				<button type="button" class="btn btn-primary
				dropdown-toggle"
					data-toggle="dropdown">                         
				    <span data-bind="label">Year</span>&nbsp;
                                    <span class="caret"></span>
				</button> <ul class="dropdown-menu" >
				    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
				</ul>                              
			    </div> 
			</div>
		    <p></p>
		    <a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
		    ('Start New Plan') ?> &raquo;</a>
		    <div class="control-group">
			<div class="controls">
			    <h4>Upload Prepared Plan File:</h4>
			<input class="input-file" id="fileInput" type="file">
			    <button type="submit" class="btn btn-primary btn-xs">Upload</button>
			    <button type="submit" class="btn btn-warning btn-xs">Cancel</button>
			</div>
		    </div>
		    </div><!--close container-->
		</div><!--close column-->
		
		<!--column 2-->
		<p></p>
                    <div class="col-md-6">
                        <p><h6>Enter answers below:</h6></p>
                        <div class="panel-group" id="accordion">
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion"
					   href="#collapseOne">Select Corresponding Student Outcome</a>
				    </h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse in">
				    <div class="panel-body">
					<div class="control-group">
					    <div class="controls">
						
						<div class="bs-example">
    <table class="table">
	<tr>
	  <th> <input type="checkbox"></th> <td>Student Outcome name</td>
	</tr> <tr class="active">
	  <td> <input type="checkbox"></td> <td>Student Outcome name</td>
	</tr>
    </table>
    <p></p>
						</div>
					    </div>
					</div>
				    </div>
				</div>
				<div class="panel panel-success">
				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion"
					       href="#collapseTwo">Question #1</a>
					</h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
					    <div class="control-group">
						<div class="controls">
						    <textarea class="input-xlarge" id="textarea"
							      rows="3"placeholder="Need to get this text box to work like this...
							      https://github.com/claystreet/bootstrap-rta..."></textarea>
						</div>
					    </div>
					</div>
				    </div>
				    <div class="panel panel-success">
					<div class="panel-heading">
					    <h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion"
						   href="#collapseThree">Question #2</a>
					    </h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse">
					    <div class="panel-body">
						<div class="control-group">
						    <div class="controls">
							<textarea class="input-xlarge" id="textarea" rows="3"
							placeholder="Need to get this text box to work like this...
							https://github.com/claystreet/bootstrap-rta..."></textarea>
						    </div>
						</div>
					    </div>
					</div>
				    </div>
				</div>
			    </div>
			</div>
<a class="btn btn-primary btn-md" href="../img/userguide.pdf"><?php echo $this->translate
            ('Preview Plan') ?> &raquo;</a>			<button type="submit" class="btn btn-primary">Submit Plan</button>
		    </div>
	    </div>
	</div>
	<script src="../js/jquery.min.js"></script>
        <script src="../js/bootstrap3-typeahead.js"></script>
        <script src="https://code.jquery.com/jquery.js"></script>
	<script src="../js/bootstrap.min.js"></script>
    </body>
</html>