<?php
// module/Student/view/mock/mock/index.phtml:

$title = 'Mock-up Home';
$this->headTitle($title);
?>
<p></p>
<html><body>
    <div class="container">
        <center><h3>NCC Acad Assessment Mock-up!</h3>
            <p>Instructions for use...</p>
            <!-- Student Outcomes button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'so'));?>"><?php echo $this->translate
            ('Student Outcomes') ?> &raquo;</a>
            <p></p>
            <!-- Plans button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'plans'));?>"><?php echo $this->translate
            ('Plans') ?> &raquo;</a>
            <p></p>
            <!-- Reports button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'reports'));?>"><?php echo $this->translate
            ('Reports') ?> &raquo;</a>
            <p></p>
        </center>
    </div>
   
</html>