<?php
// module/Student/view/student/student/edit.phtml:

$title = 'Modify Plan';
$this->headTitle($title);
?>

<html>
        <body>
    <div class="container">
      
            <center><h3>Modify Plan</h3>
                <p><h6>Instructions for use...</h6></p></center>
            
                   <div class="col-md-12">
			<center>
<div class="control-group">
    <div class="container">
    </div>
            <div class="controls">
               <img src="../img/rtabox.png" alt="..." class="img-rounded">
          <div class="form-actions">  
            <button type="submit" class="btn btn-primary">Save changes</button>  
            <button class="btn">Cancel</button>  
          </div>  
 </div>  
                    </div>
                </div>
    </div>
                    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                    <script src="https://code.jquery.com/jquery.js"></script>
                    <!-- Include all compiled plugins (below), or include individual files as needed -->
                    <script src="js/bootstrap.min.js"></script>
		    </center>
        </body>
</html>
