<?php
// module/Student/view/mock/mock/viewSO.phtml:

$title = 'Reports';
$this->headTitle($title);
?>
<html>
    <body>

	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
  
    <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
        <div class="container">
            <center><h3>Assessment Reports</h3>
            
	    </center>
	    
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <div class="container">
                       <h6>Action</h6>
                       
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="View">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Add</a></li>
                                    <li><a href="#">View</a></li>
                                    <li><a href="#">Modify</a></li>
                                </ul>
                            </div>
                        </div>
                        <h6>Department Name</h6>
                       
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science/BS</a></li>
                                    <li><a href="#">Computer Science/MS</a></li>
                                    <li><a href="#">Computer Science/BS</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Prog/Degree dropdown -->
                        <h6>Degree/Program</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="MS/Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science/BS</a></li>
                                    <li><a href="#">Computer Science/MS</a></li>
                                    <li><a href="#">Computer Science/BS</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year --> <h6>Academic Year</h6>
			<div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="2014-15">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">

                                    <span data-bind="label">Select</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>
                            </div>			    
                        </div><p></p>
			
	  <!-- Get Button trigger modal -->
<a class="btn btn-success btn-md" href="./reports">
  Submit &raquo;
</a>

<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>
                    </div><!--close container-->
                </div><!--close column-->
		<!--column 2-->
		<p></p>
		<div class="col-md-8">
		   <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <colgroup>
        <col class="col-xs-8">

      </colgroup>
     
  <div class="bs-example">
    <table class="table">
      
          <h6>Modify Report</h6>
       <h4>ACC MS/Accounting Plan #1 2014-15</h4>
      
    
    <div class="controls">
	<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Outcomes
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
<p>
 1.Students should understand a portion of the standard undergraduate mathematics curriculum, including the theoretical concepts which form the foundations of integral and differential calculus, differential equations, and elementary linear algebra.
</p>2.Students should be able to apply formulas and procedures learned in their courses in an appropriate fashion and make decisions based upon their solutions. 
  
  </div><!-- /.col-lg-6 -->      </div>
    
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
         1. Describe assessment method.
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
	<textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample"
		  placeholder="Pre-populated text to modify"></textarea>
      </div>
    </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
           2. Describe population assessed.
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
<textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample"
		  placeholder="Pre-populated text to modify"></textarea>      </div>
    </div>
    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Feedback
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
	 <div class="input-group">
      <span class="input-group-addon">
        <input type="radio" placeholder="">In need of revision &nbsp;
		<input type="radio" placeholder="">Closes loop
      </span>
    
    </div><!-- /input-group -->
<textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample"
		  placeholder="Enter feedback..."></textarea>
      </div>
    </div>
 
    </div></div></div>
	
        </div> <!-- controls -->
        <button type="button" class="btn btn-primary">Back to Reports</button>&nbsp;
	<button type="button" class="btn btn-primary">Preview</button>&nbsp;
	<button type="button" class="btn btn-primary">Save Draft</button>&nbsp;
	<button type="button" class="btn btn-success">Submit</button>&nbsp;
	
      <tbody>
       
      </tbody>
    </table></table>
  </div><!-- /example -->
   
                   
    </div>
         
             <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                        <script src="../js/jquery.min.js"></script>
                       
                        <script src="https://code.jquery.com/jquery.js"></script>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script src="../js/bootstrap.min.js"></script>
                        <script src="../js/bootstrap-rta.min.js"></script>
                        <script>
                            $(document).ready(function() {
                                document.getElementById('ta_sample').value = "";
                                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
                            });
                        </script>
    </body>
</html>

