<?php
// module/Student/view/mock/mock/viewSO.phtml:

$title = 'Plans';
$this->headTitle($title);
?>
<html>
    <body>
        <div class="container">
            <center><h3>Assessment Plans</h3>
                <p><h6>Instructions for use...</h6></p></center>
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
                        <div class="input-group" >
                            <!-- Add new Plan button -->
                            <a class="btn btn-primary btn-md" href="<?php echo $this->url
        ('mock', array('action' => 'addplan'));?>"><?php echo $this->translate('Add New Assessment Plan')
	?> &raquo;</a>
	<p></p>
			</div>
			<!-- /input-group -->
                        <h6>Enter Department Name</h6>
                        <div class="input-group">
                            <input id="dept_search" type="text" data-provide="typeahead" class="form-control"
                                   data-source='["CSC", "MTH", "ENG", "ART", "BIO"]'>
                            <div class="input-group-btn">
                                <button class="btn btn-primary"
                                        type="button">Clear</button>
                            </div>
                        </div><!-- /input-group -->
                        <!-- Prog/Degree dropdown -->
                        <h6>Select Program/Degree</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Prog/Deg appears here">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Pr/Dg
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science/BS</a></li>
                                    <li><a href="#">Computer Science/MS</a></li>
                                    <li><a href="#">Computer Science/BS</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year --> <h6>Select Academic year</h6> <div
                            class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Year appears here">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">

                                    <span data-bind="label">Year</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>

                            </div>
                        </div>
                    </div><!--close container-->
                </div><!--close column--> <!--column 2--> <p></p> <div
                    class="col-md-8">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse"
                                       data-parent="#accordion"
                                       href="#collapseOne">List of
                                        Corresponding Reports appear
                                        here...</a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <div class="control-group">
                                        <div class="controls">
                                            <div class="bs-example">
                                                <table class="table">
                                                    <tr>
                                                        <th> <input type="checkbox"></th> <td>Report name</td>
                                                    </tr> <tr class="active">
                                                        <td> <input type="checkbox"></td> <td>Report name</td>
                                                    </tr>
                                                </table>
                                                <p></p>
                                                <a class="btn btn-primary btn-lg" href="#"><?php
echo
$this->translate
        ('Get Plan')
?> &raquo;</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <p></p>
                            <div class="col-md-8">
                                Plan appears here...

                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped">

                                        <div class="bs-example">
                                            <table class="table">
                                                <tbody>
                                                    <tr class="active">
                                                        <td>1</td>
                                                        <td>Plan name</td>
                                                        <td>Report name</td>
                                                        <td>
                                                            <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
$this->translate('View Plan')
?> &raquo;</a>
                                                            <a class="btn btn-primary btn-xs" href="<?php echo $this->url
        ('mock', array('action' => 'modifyplan'));
?>"><?php echo
$this->translate('Modify Plan')
?> &raquo;</a> <p></p>
                                                        </td>
                                                    </tr>
						</tbody>
					    </table>
					</div>
				    </table>
				</div>
			    </div>

                        </div>
                    </div>
                </div><!-- /example -->
            </div><!-- /example -->
            <script src="../js/jquery.min.js"></script>
	    <script src="../js/bootstrap3-typeahead.js"></script>
	    <script src="../js/bootstrap.min.js"></script>
    </body>
</html>
