<?php
// module/Student/view/mock/mock/viewSO.phtml:

$title = 'Plans';
$this->headTitle($title);
?>
<html>
    <body>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
  
    <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
        <div class="container">
            <center><h3>Assessment Plans</h3>
            
	    </center>
	    
	    
            <p></p>  
            <div class="row">
                <div class="col-md-4">
                    <!-- Dept typeahead --> <div class="container">
            <input type="checkbox">View &nbsp;
		    <input type="checkbox">Add &nbsp;
		    <input type="checkbox">Modify            
	<p></p>
                        <h6>Department Name</h6>
                       
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">Computer Science</a></li>
                                    <li><a href="#">Accounting</a></li>
                                    <li><a href="#">Science</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Prog/Degree dropdown -->
                        <h6>Degree/Program</h6>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="MS/Accounting">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">Select
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu">
                                    <li><a href="#">BS/Accounting</a></li>
                                    <li><a href="#">MS/Accounting</a></li>
                                    <li><a href="#">MA/Accounting</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Year --> <h6>Academic Year</h6>
			<div class="input-group">
                            <input type="text" class="form-control"
                                   placeholder="2014-15">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary
                                        dropdown-toggle"
                                        data-toggle="dropdown">

                                    <span data-bind="label">Select</span>&nbsp;
                                    <span class="caret"></span>
                                </button> <ul class="dropdown-menu" >
                                    <li><a href="#">Current</a></li>
                                    <li><a href="#">2015-16</a></li>
                                    <li><a href="#">2016-17</a></li>
                                    <li><a href="#">2017-18</a></li>
                                </ul>
                            </div>			    
                        </div><p></p>
			
	  <!-- Get Button trigger modal -->
<a class="btn btn-success btn-md" href="./plans">
  Submit &raquo;
</a>

<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>
                    </div><!--close container-->
                </div><!--close column-->
		<!--column 2-->
		<p></p>
		<div class="col-md-8">
		</div></div>
    </body>
</html>
