<?php
// module/Student/view/mock/mock/viewSO.phtml:

$title = 'Student Outcomes';
$this->headTitle($title);
?>
<html>
    <body>
	<div class="container">
	    <center><h3>Student Outcomes</h3>
		<p><h6>Instructions for use...</h6></p></center>
	    <div class="row">
		<div class="col-md-4">
                    <!-- Dept typeahead -->
		    <div class="container">
			 
			 <div class="input-group" >
    

	<!-- Add new Student Outcomes button -->
            <a class="btn btn-primary btn-md" href="<?php echo $this->url
            ('mock', array('action'=>'addoutcm'));?>"><?php echo $this->translate
            ('Add Student Outcomes') ?> &raquo;</a>
            <p></p>  
    </div><!-- /input-group -->
			
			
			<h6>Enter Department Name</h6>
			<div class="input-group">
			    <input type="text" class="form-control" placeholder="Type ahead here...">
				<span class="input-group-btn">
				    <button class="btn btn-primary" type="button">Enter</button>
				</span>
			</div><!-- /input-group -->
			
                        <!-- Prog/Degree dropdown -->
			<h6>Select Program/Degree</h6>
			<div class="input-group">
			    <div class="input-group-btn">
				<button type="button" class="btn btn-primary dropdown-toggle"
					data-toggle="dropdown">Select
				    <span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
				    <li><a href="#">Computer Science/BS</a></li>
				    <li><a href="#">Computer Science/MS</a></li>
				    <li><a href="#">Computer Science/BS</a></li>
				</ul>
			    </div>
			    <input type="text" class="form-control" placeholder="Prog/Deg appears here">
			</div>
                   
                        <!-- Year  -->
			<h6>Select Academic year</h6>
			<div class="input-group">
			    <div class="input-group-btn">
				<button type="button" class="btn btn-primary dropdown-toggle"
					data-toggle="dropdown">2014-15
				    <span class="caret"></span>
				</button>
				<ul class="dropdown-menu" >
				    <li><a href="#">2015-16</a></li>
				    <li><a href="#">2016-17</a></li>
				    <li><a href="#">2017-18</a></li>
				</ul>
			    </div>
			    <input type="text" class="form-control" placeholder="Year appears here">
			</div>
			<p></p>
			<a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
            ('Get Outcomes') ?> &raquo;</a>
		    </div><!--close container-->
		</div><!--close column-->
		<!--column 2-->
		<p></p>
		<div class="col-md-8">
		   <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <colgroup>
        <col class="col-xs-8">
        
      </colgroup>
      <thead>
        <tr>
          <th>List of Student Outcomes appears here...</th>
       
        </tr>
      </thead>
      
  <div class="bs-example">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Column heading</th>
          <th>Column heading</th>
          <th>Option</th>
        </tr>
      </thead>
      <tbody>
        <tr class="active">
          <td>1</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>
       <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a>
    </td>
        </tr>
        <tr>
          <td>2</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr class="success">
          <td>3</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr>
          <td>4</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr class="info">
          <td>5</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr>
          <td>6</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr class="warning">
          <td>7</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr>
          <td>8</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
        <tr class="danger">
          <td>9</td>
          <td>Column content</td>
          <td>Column content</td>
          <td>  <a class="btn btn-primary btn-xs" href="../img/userguide.pdf"><?php echo
	    $this->translate ('View SO') ?> &raquo;</a>
         <a class="btn btn-primary btn-xs" href="<?php echo $this->url
	    ('mock', array('action'=>'modifyso'));?>"><?php echo
	    $this->translate ('Modify SO') ?> &raquo;</a>
	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Deactivate') ?> &raquo;</a></td>
        </tr>
      </tbody>
    </table>
  </div><!-- /example -->
                    <script src="js/jquery-1.8.3.min.js"></script>
                    <script src="js/bootstrap3-typeahead.js"></script>
                    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                    <script src="https://code.jquery.com/jquery.js"></script>
                    <!-- Include all compiled plugins (below), or include individual files as needed -->
                    <script src="js/bootstrap.min.js"></script>
		    <script src="js/bootstrap-select.min.js"></script>
        </body>
</html>
