<?php
// module/Student/view/mock/mock/viewSO.phtml:

$title = 'Student Outcomes';
$this->headTitle($title);
?>
<html>
    <body>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
  
    <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
	<div class="container">
	    <center><h3>Student Outcomes</h3><div class="input-group" >
    
</center>
	<!-- Add new Student Outcomes button -->
         
	    


	    
	    
	    
            <p></p>  
    </div><!-- /input-group -->
		<p></p>
	    
	    <div class="row">
		<div class="col-md-4">
                    <!-- Dept typeahead -->
		    <div class="container">
			 

			<h6>Department Name</h6>
                        <div class="input-group">
			   
                            <input type="text" class="form-control"
			    placeholder="Accounting">
                                 <div class="input-group-btn">
				<button type="button" class="btn btn-primary
				dropdown-toggle"
					data-toggle="dropdown">Select
				    <span class="caret"></span>
				</button> <ul class="dropdown-menu">
				    <li><a href="#">Computer Science</a></li>
				    <li><a href="#">Biology</a></li>
				    <li><a href="#">Science</a></li>
				</ul>
			    </div>
			
			</div><!-- /input-group -->
			<!-- Prog/Degree dropdown -->
                        <h6>Degree/Program</h6>
                        <div class="input-group">
			   
                            <input type="text" class="form-control"
			    placeholder="MS/Accounting">
                                 <div class="input-group-btn">
				<button type="button" class="btn btn-primary
				dropdown-toggle"
					data-toggle="dropdown">Select
				    <span class="caret"></span>
				</button> <ul class="dropdown-menu">
				    <li><a href="#">BS/Computer Science</a></li>
				    <li><a href="#">MS/Computer Science</a></li>
				    <li><a href="#">MA/Computer Science</a></li>
				</ul>
			    </div>			

			</div>
			<p></p>
			<a class="btn btn-primary btn-md" href="./so"><?php echo $this->translate
            ('View Outcomes') ?> &raquo;</a>
<a class="btn btn-primary btn-md" href="./soaddout">
  Add Outcome &raquo;
</a>
<p></p>
<a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo
	    $this->translate ('Back to Main') ?> </a> <p></p>			
		    </div><!--close container-->
		</div><!--close column-->
		<!--column 2-->
		<p></p>
		<div class="col-md-8">
		   <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <colgroup>
        <col class="col-xs-8">

      </colgroup>
     
  <div class="bs-example">
    <table class="table">
      
          <h6>List of Outcomes for MS/Accounting in Accounting</h6>
       
      <tbody>
        <tr class="active">
          <td>1</td>
          <td>Students should understand and apply generally accepted accounting principles appropriate for introductory level courses.
</td>
          
          <td>
      
         <!-- Button trigger modal -->
<a class="btn btn-primary btn-xs" href="./modifyout">
  Modify &raquo;
</a>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">ACC Corporate Track/BA Outcome #1</h4>
      </div>
      <div class="modal-body">
    <div class="controls">
	<textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Students should understand and apply generally accepted accounting principles appropriate for introductory level courses."></textarea>
        </div> <!-- controls -->
                                        
                      
      <div class="modal-footer">
      
        <button type="button" class="btn btn-primary">Close</button>
	<button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
  </div>

	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Delete') ?> &raquo;</a></td>
        </tr>
       
        <tr>
          <td>2</td>
          <td>Students should be able to evaluate and communicate basic accounting information effectively, sometimes using technology.
</td>
          <td>  
          <!-- Button trigger modal -->
<button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal2">
  Modify &raquo;
</button>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModal2Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModal2Label">ACC Corporate Track Outcome #2</h4>
      </div>
      <div class="modal-body">
         <div class="controls">
             <textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Students should understand and apply generally accepted accounting principles appropriate for introductory level courses."></textarea>
                 </div> <!-- controls -->        
      </div>
      <div class="modal-footer">
 
        <button type="button" class="btn btn-primary">Close</button>
	<button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
  </div>

	    <a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Delete') ?> &raquo;</a></td>
        </tr>
       
        <tr class="active">
          <td>3</td>
          <td>Students should understand and apply generally accepted accounting principles to business entities.
</td>
          
          <td>  
         <!-- Button trigger modal -->
<button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal3">
  Modify &raquo;
</button><a class="btn btn-warning btn-xs" href="#"><?php echo
	    $this->translate ('Delete') ?> &raquo;</a>

<!-- Modal -->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModal3Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModal3Label">ACC Corporate Track Outcome #3</h4>
      </div>
      <div class="modal-body">
	<div class="controls">
            <textarea rows="6" cols="60" class="rta" id="ta_sample" name="ta_sample" placeholder="Students should understand and apply generally accepted accounting principles appropriate for introductory level courses."></textarea>
                                            </div> <!-- controls -->
                                  
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-primary">Close</button>
	<button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
  </div>

	    </td>
        </tr>
       
      </tbody>
    </table></table>
  </div><!-- /example -->

    </div>
	 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	                <script src="../js/bootstrap.min.js"></script>
                        <script src="../js/jquery.min.js"></script>
                        <script src="../js/bootstrap3-typeahead.js"></script>
                        <script src="https://code.jquery.com/jquery.js"></script>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script src="../js/bootstrap-rta.min.js"></script>
                        <script>
                            $(document).ready(function() {
                                document.getElementById('ta_sample').value = "";
                                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
                            });
                        </script>
                    </div>

        </body>
</html>
