<center><h3>Administrator Queries</h3></center>
<div class = "panel panel-default">
    <div class="panel-body">
    
    <div class="col-md-4">
        <!-- Choose Query -->
        <dl>
            <dt>Query 1:<br />
            Show programs missing plans.
            </dt>
            <dd>
             <!-- Choose Years -->
            <select class="selectpicker" id="q1year" name="q1year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
            </dd>
        </dl>
        <dl>
            <dt>Query 2:<br />
            Show programs missing reports.
            </dt>
            <dd>
             <!-- Choose Years -->
            <select class="selectpicker" id="q2year" name="q2year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
            </dd>
        </dl>
        <dl>
            <dt>Query 3:<br />
            Show programs conducting meta assessment.
            </dt>
            <dd>
            <!-- Choose Years -->
            <select class="selectpicker" id="q3year" name="q3year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
             </dd>
        </dl>
        <dl>
            <dt>Query 4:<br />
            Show programs requesting funding.
            </dt>
            <dd>
               <!-- Choose Years -->
            <select class="selectpicker" id="q4year" name="q4year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
          </dd>
        </dl>
        <dl>
            <dt>Query 5:<br/>
            Show programs that have modified their outcomes.
            </dt>
            <dd> 
            </dd>
        </dl>
        <dl>
            <dt>Query 6:<br/>
            Show programs that have added or modified last year's plan.
            
            <button type="button" class="btn-primary" id="query6">Go</button>
            </dt>
            <dd></dd>
        </dl>
        <dl>
            <dt>Query 7:<br/>
            Show programs that have added or modified last year's report.
            
            <button type="button" class="btn-primary" id="query7">Go</button>
            </dt>
            <dd></dd>
        </dl>
        <br />
        <!-- Choose Query -->
        <dl>
            <dt>Show all programs that have not added a plan for a specific year.
             
            <div class="form-group">
                <div class='input-group date' id='dp5'>
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                <input type='text' class="form-control" id='q5date'/>
               <input type='text' class="datepicker" id='q5date'/>
               
                </div>
            </div>
     
    </div><!--close column-->


    <!--column 2 - this holds the partial-->
    <div class="col-md-8">
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="resultsTable" name="resultsTable">
            </table>
        </div> <!-- end of table-responsive -->
          
    </div> <!-- end of col-md-8--> 
  </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../js/bootstrap.min.js"></script> 
<script src="../js/bootstrap-rta.min.js"></script>
<script src="../js/bootstrap-select.js"></script>
<script src="../js/bootstrap-datepicker.js"></script>
<script>

$(document).ready(function () {
    
    // set years for year dropdowns
    var currentYear = new Date().getFullYear();
    
    $('#q1year').append('<option  data-hidden="true"></option>');
    for (var year = currentYear; year > 2005; year--){
        $('#q1year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
    }
    $('#q1year').selectpicker('refresh');
   
   
    $('#q2year').append('<option  data-hidden="true"></option>');
    for (var year = currentYear; year > 2005; year--){
        $('#q2year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
    }
    $('#q2year').selectpicker('refresh');
    
    
    $('#q3year').append('<option  data-hidden="true"></option>');
    for (var year = currentYear; year > 2005; year--){
        $('#q3year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
    }
    $('#q3year').selectpicker('refresh');
    
    
    $('#q4year').append('<option  data-hidden="true"></option>');
    for (var year = currentYear; year > 2005; year--){
        $('#q4year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
    }
    $('#q4year').selectpicker('refresh');
     $('.datepicker').datepicker();
  //  $('#q5date').datepicker({dateFormat: 'mm-dd-yyyy'});
})

$(document).on('click', '#dp5', function(){
    $('#dp5').datepicker().on('changeDate', function(ev){
       var date = new Date(ev.date);
       $('#q5date').val(date);
       $('#q5date').datepicker({dateFormat: 'mm-dd-yyyy'});
      
    })
})


$(document).on('change', '#q1year', function () {
    // clear rhs of page
    $('#resultsTable').html("");

    // get dropdown value
    var year = $('#q1year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q1year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery1')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});


$(document).on('change', '#q2year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q2year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q2year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery2')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('change', '#q3year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q3year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q3year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery3')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('change', '#q4year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q4year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q4year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery4')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});


$(document).on('click', '#query5', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q5year').val();
    
    // validate year
    if (validateYear(year)){
        document.getElementById("q5error").style.display="none";
    
        // create url for redirect url(route, array(controller, action))
        var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery5')); ?>";
        urlform = urlform + '/' + year;
        ajaxCall(urlform);
    }
    else{
        document.getElementById("q5error").style.display="block";
    }
});

$(document).on('click', '#query6', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery6')); ?>";
    ajaxCall(urlform);
});

$(document).on('click', '#query7', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery7')); ?>";
    ajaxCall(urlform);
});

function ajaxCall(urlform){
            // asynchronous ajax code to populate program/degree selector
        $.ajax({
          url: urlform,
          type: "GET",
          // dataType returned from server
          dataType: "html",
          error : function(xhr, status, error) {
             console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
          },
          success: function(results){
            // clear any existing html in the partial div
            $('#resultsTable').html("");
            $('#resultsTable').html(results);        
          },
       });
}

function resetDropDowns(){
    // reset dropdowns except dropdown matching parameter
    $('select[name=q1year]').val(1);
    $('select[name=q2year]').val(1);
    $('select[name=q3year]').val(1);
    $('select[name=q4year]').val(1);
    $('.selectpicker').selectpicker('refresh');
}
   
</script>

