<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('NCC '. $this->translate('Acad Assessment Mock-up'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/ncctower'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-rta.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-rta.min.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-rta.min.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('mock') ?>"><img src="<?php echo $this->basePath('img/ncctower.jpg') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('NCC Acad Assessment Mock-up') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="http://noctrl.edu"><?php echo $this->translate('NCC Home') ?></a></li>
                     <li class="active"><a href="http://its.noctrl.edu"><?php echo $this->translate('Contact IT') ?></a></li>
                    <li class="active"><a href="mailto:silahi@noctrl.edu"><?php echo $this->translate('Contact Admin') ?></a></li>

                     <li class="active"><a href="./img/userguide.pdf" ><?php echo $this->translate('User Guide') ?></a></li>
                    
                    </ul>
                    <!-- The drop down menu -->
       <ul class="nav navbar-nav navbar-right">
  
          <li class="dropdown">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Login <span class="caret"></span>
  </button>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
              <!-- Login form here -->
              <form action='mock' method="post" accept-charset="UTF-8">
  <input id="user_username" style="margin-bottom: 15px;" type="text" name="user[username]" size="30" />
  <input id="user_password" style="margin-bottom: 15px;" type="password" name="user[password]" size="30" />
  <input id="user_remember_me" style="float: left; margin-right: 10px;" type="checkbox" name="user[remember_me]" value="1" />
  <label class="string optional" for="user_remember_me"> Remember me</label><br>
  <a href="#">Forgot Password?</a>
  <input class="btn btn-primary" type="submit" name="commit" value="Login" />
</form>
            </div>
          </li>
        </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav> 
        <div class="container">
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 1876 - <?php echo date('Y') ?> by CSCCapstone Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
