<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('NCC '. $this->translate('NCC Academic Assessment Portal'))->setSeparator(' - ')->setAutoEscape(false) ?>


        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/ncctower'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-select.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-rta.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-rta.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-rta.css')
                        ->prependStylesheet($this->basePath() . '/css/datepicker.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
            ->prependFile($this->basePath() . '/js/bootstrap-select.js')
            ->prependFile($this->basePath() . '/js/bootstrap-rta.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-select.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="<?php echo $this->url('mock') ?>"><img src="<?php echo $this->basePath('img/ncctower.jpg') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('NCC Academic Assessment Portal') ?></a>

                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="http://noctrl.edu"><?php echo $this->translate('NCC Home') ?></a></li>
                        <li class="active"><a href="http://its.noctrl.edu"><?php echo $this->translate('Contact IT') ?></a></li>
                        <li class="active"><a href="mailto:silahi@noctrl.edu"><?php echo $this->translate('Contact Admin') ?></a></li>
                        <li class="active"><a href="./img/userguide.pdf" ><?php echo $this->translate('User Guide') ?></a></li>
                        <li class="active"><a href ="https://cardinalnet.northcentralcollege.edu/faculty/committees/assessment/"><?php echo $this->translate('Assessment Committee') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav> 
        <div class="container">
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 1876 - <?php echo date('Y') ?> by CSCCapstone Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
