<div class="row">
<?php
// module/Admin/view/program/add.phtml:

$title = 'Add new Program';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-12" style="overflow:hidden;">
    <h3>Add a New Program</h3>
    <div class="col-md-4">
    <?php echo $this->partial('admin/program/form.phtml',array('form'=>$this->form,'action' =>'add'));?>
    </div>
</div>