<div class="row">
<?php
// module/Admin/view/program/add.phtml:

$title = 'Add new Program';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('program', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="control-group col-md-4">  
    <div class="control-group">  
    <div class="form-group">
        <?php echo $this->formLabel($form->get('unit_id')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('unit_id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('active_flag')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('active_flag')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formInput($form->get('id')); ?>
    </div>
</div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div>