<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'program')); ?>
<?php
$title = 'Add new Program';
$this->headTitle($title);
?>
<div class="row">
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-12" style="overflow:hidden;">
    <h3>Add a New Program</h3>
    <div class="col-md-4">
    <?php echo $this->partial('admin/program/form.phtml',array('form'=>$this->form,'action' =>'add'));?>
    </div>
</div>