<?php
$form = $this->form;
$form->setAttribute('action', $this->url('program', array('action' => $action)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="control-group col-md-12 program-form">  
    <div class="control-group">  
    <div class="form-group">
        <?php echo $this->formLabel($form->get('unit_id')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('unit_id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('active_flag')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formCheckbox($form->get('active_flag')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formInput($form->get('id')); ?>
    </div>
</div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>