<?php // echos a header line with all the programs listed together as one string ?>
<?php
    $allPrograms = "";
    if (!empty($this->programs)) {
	foreach ($this->programs as $program) :
            $allPrograms = $allPrograms . $program . ", ";
	endforeach;
	
	// remove the last ", " added on after the last loop above
	$allPrograms = substr($allPrograms, 0, -2);
	
        echo "<h4>" . $this->label . $this->unit . ", " . $allPrograms . ", " . $this->year . "</h4>";
    }
?>