<?php

$title = 'Assessment Plan Home';
$this->headTitle($title);
?>	
	
<div class="container">
    <center><h3>Assessment Plans-HOME</h3></center>
    <p></p>  
    <div class="row">
	<div class="col-md-4">	                  
	    <form action="<?php echo $this->url('plans', array('action'=>'index'));?>" method="post">                                    				
		<div class="container">
		    <br />
		    <br />
		     <!-- Choose Action -->
		     <select class="selectpicker" id="action-menu" name="action-menu" data-style="btn-primary" title='Choose Action'>
			<option data-hidden="true"></option>
		     </select>  
		    <br />
		    <br />
		  
		     <!-- Choose Department/Unit -->
		     <select class="selectpicker" id="unit-menu" name="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
			<option data-hidden="true"></option>
		     </select>  
		    <br />
		    <br />
		  
		     <!-- Choose Program/Degree -->
		     <select class="selectpicker" id="prog-menu" name="prog-menu[]" data-style="btn-primary" title='Choose Program/Degree' multiple>
			<option data-hidden="true"></option>
		     </select>
		    <br />
		    <br />
		    <!-- Choose Years -->
		    <select class="selectpicker" id="year-menu" name="year-menu" data-style="btn-primary" title='Choose Year'>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />

		    <!-- Submit Button used to get the plan data from the database -->
		    <button type="submit" name="formListPlans" value="formListPlans" class="btn btn-success btn-md">Submit &raquo;</button>
		    <p></p>

		    <!-- Back to Main Button used to return to the main page -->
		    <a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo $this->translate ('Back to Main') ?>
		    </a>
		    <p></p>
		</div><!--close container-->
	    </form>
	</div><!--close column-->
	
	<!--column 2-->
	<div class="col-md-6">
	    <p>This is where the plan or report will pop up with a feedback box.</p>
	    <style>
	       textarea {
		  width: 400px;
	       }
	    </style>
	    <div class="container">
	       <form class="form-horizontal" name="rtaform" id="rtaform" method="GET" action="#">
		  <div class="control-group">
		    <label class="control-label" for="ta_sample">Feedback Response</label>
		    <div class="controls">
		       <textarea rows="8" cols="60" class="rta" id="ta_sample" name="ta_sample"></textarea>
		    </div> <!-- controls -->
		  </div> <!-- control-group -->
	       </form>
	    </div>
	</div>
    </div>
</div>
 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="./js/bootstrap.min.js"></script> 
<script src="./js/bootstrap-rta.min.js"></script>
<script src="./js/bootstrap-select.js"></script>

<script src="../js/bootstrap.min.js"></script>
<script src="../js/bootstrap-rta.min.js"></script>
<script src="../js/bootstrap-select.js"></script>

<script>

// load actions based on user privileges
$(document).ready(function() {
     $.rta(); // load rta features - simplest implementation

   var actions = <?php print json_encode($useractions); ?>;
   for (var i = 0; i < actions.length; i++){
      $('#action-menu').append('<option>' + actions[i] + '</option>');
   }
   
   // call code to initialize the selectpicker
   // this must come after the options are initialized
   $('.selectpicker').selectpicker();
});

// update unit/department options based on actions
$(document).on('change', '#action-menu', function () {
   $action = $('#action-menu option:selected').val();
   // clear selectorlist before adding unit/department options
   var oldSelections = $('#unit-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   // data-hidden="true" shows title on button
   $('#unit-menu').append('<option  data-hidden="true"></option>');
   $('#unit-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getUnits')); ?>";
   urlform = urlform + '/' + $action;
     
   // asynchronous ajax code to populate unit/department selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(unitsJson){
         for (var i = 0; i < unitsJson.length; i++){
            $('#unit-menu').append('<option>' + unitsJson[i].id + '</option>');
         }
         $('#unit-menu').selectpicker('refresh');
      },
   });
});

// update program options based on unit/department
$(document).on('change', '#unit-menu', function () {
   $unit = $('#unit-menu option:selected').val();
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getPrograms')); ?>";
   urlform = urlform + '/' + $unit;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
});

// load all the year options after the unit/department & unit/department are selected
$(document).on('change', '#prog-menu', function () {
   // clear selectorlist before adding all the years
   var oldSelections = $('#year-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   // data-hidden="true" shows title on button
   $('#year-menu').append('<option  data-hidden="true"></option>');
   $('#year-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getYears')); ?>";
   urlform = urlform;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#year-menu').append('<option>' + programsJson[i].year + '</option>');
         }
         $('#year-menu').selectpicker('refresh');
      },
   });
});
</script>		
