<?php
// module/Mock/view/mock/mock/add.phtml:

$title = 'Add New Assessment Plan';
$this->headTitle($title);
?>	
<html>
     <head>
        <meta charset="utf-8">
	    
	<?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/customPlan.js')
            ;
	?>

     </head>
    <body>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../css/bootstrap.min.css"> 
        <link rel="stylesheet" href="../css/bootstrap-rta.min.css">
        <style>
	 textarea {
            width: 300px;
	    }
	</style>
	
	<div class="container">
	    <center><h3>Assessment Plans</h3></center>
            <p></p>  
            <div class="row">
                <div class="col-md-4">
		    
		    <form action="<?php echo $this->url('plans', array('action'=>'index'));?>" method="post">                                    				
			<div class="container">
			    <p></p>
			
			    <!-- Action dropdown -->
			    <h6>Action</h6>                    
			    <div class="input-group">
				<input type="text" class="form-control" placeholder="Selection Appears Here" id="textAction" name="textAction"
				    <?php
					// check to see if there is a value returned from the response
					if ($returnAction != null) {
					    getValue($returnAction);
					}
				    ?>				       
				>
				<div class="input-group-btn">
				    <button type="button" class="btn btn-primary
					    dropdown-toggle"
					    data-toggle="dropdown">Select
					<span class="caret"></span>
				    </button>
				    <ul class="dropdown-menu dropdown-action">
					<li><a href="#">Add</a></li>
					<li><a href="#">Modify</a></li>
					<li><a href="#">View</a></li>
				    </ul>
				</div>
			    </div>
			    
			    <!-- Department dropdown -->
			    <h6>Department Name</h6>                    
			    <div class="input-group">
				<input type="text" class="form-control" placeholder="Selection Appears Here" id="textDepartment" name="textDepartment"
				    <?php
					// check to see if there is a value returned from the response
					if ($returnDepartment != null) {
					    getValue($returnDepartment);
					}
				    ?>				       
				>
				<div class="input-group-btn">
				    <button type="button" class="btn btn-primary
					    dropdown-toggle"
					    data-toggle="dropdown">Select
					<span class="caret"></span>
				    </button>
				    <ul class="dropdown-menu dropdown-department">
					<li><a href="#">CSC</a></li>
					<li><a href="#">Science</a></li>
					<li><a href="#">Math</a></li>
				    </ul>
				</div>
			    </div>
			    
			    <!-- Prog/Degree dropdown -->
			    <h6>Degree/Program</h6>
			    <div class="input-group">
				<input type="text" class="form-control" placeholder="Selection Appears Here" id="textProgram" name="textProgram" 
				    <?php
				    	// check to see if there is a value returned from the response
					if ($returnProgram != null) {
					    getValue($returnProgram);
					}
				    ?>				       
				>
				<div class="input-group-btn">
				    <button type="button" class="btn btn-primary
					    dropdown-toggle"
					    data-toggle="dropdown">Select
					<span class="caret"></span>
				    </button>
				    <ul class="dropdown-menu dropdown-program">
					<li><a href="#">BS Computer Science</a></li>
					<li><a href="#">MS Computer Science</a></li>
					<li><a href="#">MA Computer Science</a></li>
				    </ul>
				</div>
			    </div>
    
			    <!-- Year --> <h6>Academic Year</h6>
			    <div class="input-group">
				<input type="text" class="form-control" placeholder="Selection Appears Here" id="textYear" name="textYear"
				    <?php
					// check to see if there is a value returned from the response
					if ($returnYear != null) {
					    getValue($returnYear);
					}
				    ?>				       
				>
				<div class="input-group-btn">
				    <button type="button" class="btn btn-primary
					    dropdown-toggle"
					    data-toggle="dropdown">
    
					<span data-bind="label">Select</span>&nbsp;
					<span class="caret"></span>
				    </button>
				    <ul class="dropdown-menu dropdown-year" >
					<li><a href="#">2011</a></li>
					<li><a href="#">2012</a></li>
					<li><a href="#">2013</a></li>
				    </ul>
				</div>			    
			    </div>
			    <p></p>
			    
			    <!-- Submit Button used to get the plan data from the database -->
			    <button type="submit" name="formGetPlan" value="formGetPlan" class="btn btn-success btn-md" onclick="planValidation()">Submit &raquo;</button>
			    <p></p>
			    
			    <!-- Back to Main Button used to return to the main page -->
			    <a class="btn btn-primary btn-md" onclick="planAlert()" href="../mock">&laquo;<?php echo $this->translate ('Back to Main') ?></a>
			    <p></p>
			</div><!--close container-->
		    </form>
                </div><!--close column-->
				
		
		<!--column 2 Right side of the acreen-->
		<p></p>
                <div class="col-md-6">
		     <div class="input-group">
                        <div class="panel-group" id="accordion">
    			    <div class="panel panel-success">
    
				<?php
				    // Loop through all the returned plans
				    $planCount = 0;
				    if (!empty($plans)) {
					foreach ($plans as $plan) :
					    $planCount++;
				?>
					    <!-- Create the plan row -->
					    <div class="panel-heading">
						<h4 class="title">
						    <a data-toggle="collapse" data-parent="#accordion"
							   href="#collapse<?php getCount($planCount) ?>">Plan # <?php getCount($planCount) ?> &nbsp; </a>
						
						    <?php
							if ($returnAction == "View") {
							    $page="viewonlyplan";
							}
							else {
							    $page="modifyplan";
							}
						    ?>
						
						    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('plans',
														    array('action'=>$page,
															  'type' => $returnAction,
														          'planId' => $plan['planId'],
															  'department' => $returnDepartment,
															  'program' => $returnProgram,
															  'year' => $returnYear
														  ));
											    ?>"><?php echo $this->translate ('Select') ?> &raquo;</a>&nbsp;
											    

						</h4>
					    </div>
		    
					    <!-- Create the data for each row -->
					    <div id="collapse<?php getCount($planCount) ?>" class="pane<?php getCount($planCount) ?>-collapse collapse">
						<div class="panel-body">
						    <div class="control-group">
							<div class="controls">
							    <table class="table">							  
								<?php
								    // loop through all the outcomes
								    $outcomeCount = 0;
								    if (!empty($outcomes)) {
									foreach ($outcomes as $outcome) :
									    
									    //Check to see if the outcome exists for the plan id
									    if($plan['planId'] == $outcome->getPlanId()) {
										$outcomeCount++;
								?>				
										<tr>
										    <th><?php getCount($outcomeCount) ?>.</th> <td> <?php echo $outcome->getOutcomeText() ?></td>
										</tr>
								<?php
									    }
									endforeach;
								    }
								?>				
							    </table>
							</div>
						    </div>
						</div>
					    </div>
				<?php
					    endforeach;
				    }
				?>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
 

	<?php
	    // All php functions
	    function getValue($value)
	    {
		echo "value=\"$value\"";
	    }
	    
	    function getCount($count)
	    {
		echo $count;
	    }
	?>

	<!-- All Java Script functions -->
        <script>
	    
            $(document).ready(function() {
	        document.getElementById('ta_sample').value = "";
                $.rta(); // The simplest initialization... default button set on all class="rta" textarea's
            });

	    $(".dropdown-department li a").click(function(){
	      document.getElementById("textDepartment").value = $(this).text();
	    });
			    
	    $(".dropdown-program li a").click(function(){
	      document.getElementById("textProgram").value = $(this).text();
	    });
	
	    $(".dropdown-year li a").click(function(){
	      document.getElementById("textYear").value = $(this).text();
	    });
	    
	    $(".dropdown-action li a").click(function(){
	      document.getElementById("textAction").value = $(this).text();
	    });
	    
	    // Enable the radio buttons
	    $('.btn').button();
        </script>
    </body>
</html>









