<?php

$title = 'Assessment Plan Home';
$this->headTitle($title);
?>	
	
<div class="container">
    <center><h3>Assessment Plans-HOME</h3></center>
    <p></p>  
    <div class="row">
	<div class="col-md-4">	                  
	    <form action="<?php echo $this->url('plans', array('action'=>'index'));?>" method="post">                                    				
		<div class="container">
		    <br />
		    <br />
		    <!-- Choose Action -->
		    <select class="selectpicker" id="action-menu" name="action-menu" data-style="btn-primary" title='Choose Action'>
			<option data-hidden="true"></option>
			<option>View</option>
			<option>Add</option>
			<option>Modify</option>
		    </select>  
		    <br />
		    <br />
		    <!-- Choose Department/Unit -->
		    <select class="selectpicker" id="unit-menu" name="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
			<option data-hidden="true"></option>
		    </select>  
		    <br />
		    <br />
		    <!-- Choose Program/Degree -->
		    <select class="selectpicker" id="prog-menu" name="prog-menu[]" data-style="btn-primary" title='Choose Program/Degree' multiple>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />
		    <!-- Choose Years -->
		    <select class="selectpicker" id="year-menu" name="year-menu" data-style="btn-primary" title='Choose Year'>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />

		    <!-- Submit Button used to get the plan data from the database -->
		    <button type="submit" name="formListPlans" value="formListPlans" class="btn btn-success btn-md">Submit &raquo;</button>
		    <p></p>

		    <!-- Back to Main Button used to return to the main page -->
		    <a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo $this->translate ('Back to Main') ?>
		    </a>
		    <p></p>
		</div><!--close container-->
	    </form>
	</div><!--close column-->
    </div>
</div>
 
<!--column 2 Right side of the acreen-->
<p></p>
<div class="col-md-6">
     <div class="input-group">
	<div class="panel-group" id="accordion">
	    <div class="panel panel-success">

		<?php
		    // Loop through all the returned plans
		    $planCount = 0;
		    if (!empty($plans)) {
			foreach ($plans as $plan) :
			    $planCount++;
		?>
			    <!-- Create the plan row -->
			    <div class="panel-heading">
				<h4 class="title">
				    <a data-toggle="collapse" data-parent="#accordion"
					   href="#collapse<?php getCount($planCount) ?>">Plan # <?php getCount($planCount) ?> &nbsp; </a>
				    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('plans',
												    array('action'=>'viewonlyplan',
													  'planId' => $plan['planId'],
													  'department' => $returnDepartment,
													  'program' => $returnProgram,
													  'year' => $returnYear
												  ));
									    ?>"><?php echo $this->translate ('View') ?> &raquo;</a>&nbsp;

				    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('plans',
												    array('action'=>'modifyplan',
													  'planId' => $plan['planId'],
													  'department' => $returnDepartment,
													  'program' => $returnProgram,
													  'year' => $returnYear
												  ));
									    ?>"><?php echo $this->translate ('Modify') ?> &raquo;</a>
				</h4>
			    </div>

			    <!-- Create the data for each row -->
			    <div id="collapse<?php getCount($planCount) ?>" class="pane<?php getCount($planCount) ?>-collapse collapse">
				<div class="panel-body">
				    <div class="control-group">
					<div class="controls">
					    <table class="table">							  
						<?php
						    // loop through all the outcomes
						    $outcomeCount = 0;
						    if (!empty($outcomes)) {
							foreach ($outcomes as $outcome) :

							    //Check to see if the outcome exists for the plan id
							    if($plan['planId'] == $outcome->getPlanId()) {
								$outcomeCount++;
						?>				
								<tr>
								    <th><?php getCount($outcomeCount) ?>.</th> <td> <?php echo $outcome->getOutcomeText() ?></td>
								</tr>
						<?php
							    }
							endforeach;
						    }
						?>				
					    </table>
					</div>
				    </div>
				</div>
			    </div>
		<?php
			    endforeach;
		    }
		?>
	    </div>
	</div>
    </div>
</div>
</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-rta.min.js"></script>
<script src="js/bootstrap-select.js"></script>
<script>

// call loadDepts on page load
$(document).ready(function() {
   $.rta(); // load rta features - simplest implementation
   loadUnits();
});

// function to create department/unit options
function loadUnits(){
   
   // convert php array into javascript array
   var units = <?php print json_encode($units); ?>;
   // assign unit ids to html dropdown
   for (var i = 0; i < units.length; i++){
      $('#unit-menu').append('<option>' + units[i].id + '</option>');
   }

    // convert php array into javascript array
    var years = <?php print json_encode($years); ?>;
    // assign years to html dropdown
    for (var i = 0; i < years.length; i++){
      $('#year-menu').append('<option>' + years[i].year + '</option>');
    }
    
   // call code to initialize the selectpicker
   // this must come after the options are initalized
   $('.selectpicker').selectpicker();
   

}

// call loadPrograms when user chooses a department/unit
$(document).on('change', '#unit-menu', function () {
    loadPrograms($('#unit-menu option:selected').val());
});

// function to create program options based on department/unit chosen
function loadPrograms($unit){
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'get')); ?>";
   urlform = urlform + '/' + $unit;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
}
</script>

