<?php

$title = 'Assessment Plan View List';
$this->headTitle($title);
?>	
	
<div class="container">
    <center><h3>Assessment Plans-VIEW List</h3></center>
    <p></p>  
    <div class="row">
	<div class="col-md-4">		    
	    <form action="<?php echo $this->url('plans', array('action'=>'index'));?>" method="post">                                    				
		<div class="container">
		    <br />
		    <br />
		    <!-- Choose Action -->
		    <select class="selectpicker" name="action-menu" id="action-menu" data-style="btn-primary" title='<?php echo $action ?>'>
			<option data-hidden="true"></option>
		    </select>  
		    <br />
		    <br />
		    <!-- Choose Department/Unit -->
		    <select class="selectpicker" name="unit-menu" id="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
			<option data-hidden="true"></option>
		    </select>  
		    <br />
		    <br />
		    <!-- Choose Program/Degree -->
		    <select class="selectpicker" name="prog-menu[]" id="prog-menu" data-style="btn-primary"
			    title='Choose Program/Degree
				    <?php
					// loop through all the outcomes
					//	    if (!empty($programs)) {
					//		foreach ($programs as $program) :
					//		    echo $program . ", ";
					//		endforeach;
					//	    }
				    ?>
				  '
			    multiple>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />
		    <!-- Choose Years -->
		    <select class="selectpicker" name="year-menu" id="year-menu" data-style="btn-primary" title='Choose Year'>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />

		    <!-- Submit Button used to get the plan data from the database -->
		    <button type="submit" name="formGetPlan" value="formGetPlan" class="btn btn-success btn-md">Submit &raquo;</button>
		    <p></p>

		    <!-- Back to Main Button used to return to the main page -->
		    <a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo $this->translate ('Back to Main') ?>
		    </a>
		    <p></p>
		</div><!--close container-->
	    </form>
	</div><!--close column-->

    
	<!--column 2 Right side of the acreen-->
	<p></p>
	<div class="col-md-6">
	    <?php
		// identify the action to drive the next page to go to
		$nextPage="modifyplan";
		$label="Select a plan to modify for: ";
		if ($action == "View"){
		    $nextPage="viewonlyplan";
		    $label="Select a plan to view for: ";
		}
		
		if (sizeof($plans) == 0) {
		    $label="There are no plans for: ";
		}
			    
		$allPrograms = "";
		if (!empty($programs)) {
		    foreach ($programs as $program) :
			$allPrograms = $allPrograms . $program . ", ";
		    endforeach;
		}
	    ?>
			
	    <h4><?php echo $label . $unit . ", " . $allPrograms . $year ?></h4>
			
	     <div class="input-group">
		<div class="panel-group" id="accordion">
		    <div class="panel panel-success">
				    
			<?php
					    			
			    // Loop through all the returned plans
			    $planCount = 0;
			    if (!empty($plans)) {
				foreach ($plans as $plan) :
				    $planCount++;
			?>
			
				    <!-- Create the plan row -->
				    <div class="panel-heading">
					<h4 class="title">					
					    <a data-toggle="collapse" data-parent="#accordion"
						   href="#collapse<?php getCount($planCount) ?>">Plan # <?php getCount($planCount) ?> &nbsp; </a>
					
					<a class="btn btn-primary btn-xs" href="<?php echo $this->url('plans',
												    array('action'=>$nextPage,
													  'id' => $plan['planId'],
												  ));
									    ?>"><?php echo $this->translate ('Select') ?> &raquo;</a>&nbsp;
					
					</h4>
				    </div>
				    

			    <!-- Create the data for each row -->
			    <div id="collapse<?php getCount($planCount) ?>" class="pane<?php getCount($planCount) ?>-collapse collapse">
				<div class="panel-body">
				    <div class="control-group">
					<div class="controls">
					    <table class="table">							  
						<?php
						    // loop through all the outcomes
						    $outcomeCount = 0;
						    if (!empty($outcomes)) {
							foreach ($outcomes as $outcome) :

							    //Check to see if the outcome exists for the plan id
							    if($plan['planId'] == $outcome->getPlanId()) {
								$outcomeCount++;
						?>				
								<tr>
								    <th><?php getCount($outcomeCount) ?>.</th> <td> <?php echo $outcome->getOutcomeText() ?></td>
								</tr>
						<?php
							    }
							endforeach;
						    }
						?>				
					    </table>
					</div>
				    </div>
				</div>
			    </div>
		<?php
			    endforeach;
		    }
		?>
			
	
			
			
		    </div>
		</div>
	    </div>
	</div>

    </div>
</div>

	<?php
	    // All php functions
	    function getValue($value)
	    {
		echo "value=\"$value\"";
	    }
	    
	    function getCount($count)
	    {
		echo $count;
	    }
	?>
 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
<script src="../js/bootstrap-rta.min.js"></script>
<script src="../js/bootstrap-select.js"></script>

<script>

// load actions based on user privileges
$(document).ready(function() {
     $.rta(); // load rta features - simplest implementation

   // clear selectorlist before adding unit/department options
   var oldSelections = $('#action-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   var actions = <?php print json_encode($useractions); ?>;
   for (var i = 0; i < actions.length; i++){
      $('#action-menu').append('<option>' + actions[i] + '</option>');
   }
   
   // call code to initialize the selectpicker
   // this must come after the options are initialized
   $('.selectpicker').selectpicker();
});

// update unit/department options based on actions
$(document).on('change', '#action-menu', function () {
   $action = $('#action-menu option:selected').val();
   // clear selectorlist before adding unit/department options
   var oldSelections = $('#unit-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   // data-hidden="true" shows title on button
   $('#unit-menu').append('<option  data-hidden="true"></option>');
   $('#unit-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getUnits')); ?>";
   urlform = urlform + '/' + $action;
     
   // asynchronous ajax code to populate unit/department selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(unitsJson){
         for (var i = 0; i < unitsJson.length; i++){
            $('#unit-menu').append('<option>' + unitsJson[i].id + '</option>');
         }
         $('#unit-menu').selectpicker('refresh');
      },
   });
});

// update program options based on unit/department
$(document).on('change', '#unit-menu', function () {
   $unit = $('#unit-menu option:selected').val();
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getPrograms')); ?>";
   urlform = urlform + '/' + $unit;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
});

// load all the year options after the unit/department & unit/department are selected
$(document).on('change', '#prog-menu', function () {
   // clear selectorlist before adding all the years
   var oldSelections = $('#year-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   // data-hidden="true" shows title on button
   $('#year-menu').append('<option  data-hidden="true"></option>');
   $('#year-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getYears')); ?>";
   urlform = urlform;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#year-menu').append('<option>' + programsJson[i].year + '</option>');
         }
         $('#year-menu').selectpicker('refresh');
      },
   });
});
</script>		