    <!-- create the left hand side of the page --> 
    <div class="col-md-4" id="divNoPrint3">		    
        <div class="container">
            <br />
            <br />
            <!-- Choose Action -->
            <select class="selectpicker" id="action-menu" name="action-menu" data-style="btn-primary" title='Choose Action'>
                <option data-hidden="true"></option>
            </select>  
            <br />
            <br />
        
            <!-- Choose Department/Unit -->
            <select class="selectpicker" id="unit-menu" name="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
                <option data-hidden="true"></option>
            </select>  
            <br />
            <br />
        
            <!-- Choose Program/Degree -->
            <select class="selectpicker" id="prog-menu" name="prog-menu" data-style="btn-primary" title='Choose Program/Degree' multiple>
                <option data-hidden="true"></option>
            </select>
            <br />
            <br />
        
            <!-- Choose Years -->
            <select class="selectpicker" id="year-menu" name="year-menu" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
            <br />
            <br />
        
            <!-- Submit Button used to get the plan data from the database -->
            <button type="submit" id="formListPlans" name="formListPlans" value="formListPlans" class="btn btn-primary btn-md">Submit &raquo;</button>
            <p></p>
        </div><!--close container-->
    </div><!--close column-->
