<?php

$title = 'View Only';
$this->headTitle($title);
?>

<div class="container">
    <center><h3>Assessment Plans-VIEW Specific Plan</h3></center>
    <p></p>  
    <div class="row">
	<div class="col-md-4" id="divNoPrint1">		    
	    <form action="<?php echo $this->url('plans', array('action'=>'index'));?>" method="post">                                    				
		<div class="container">
		    <br />
		    <br />
		    
		    <!-- Choose Action -->
		    <select class="selectpicker" id="action-menu" data-style="btn-primary" title='<?php echo $action ?>'>
			<option data-hidden="true"></option>
		    </select>  
		    <br />
		    <br />

		    <!-- Choose Department/Unit -->
		    <select class="selectpicker" id="unit-menu" data-style="btn-primary" title='Choose Department/Unit'>
			<option data-hidden="true"></option>
		    </select>  
		    <br />
		    <br />

		    <!-- Choose Program/Degree -->
		    <select class="selectpicker" id="prog-menu" name="prog-menu[]" data-style="btn-primary"
			    title='Choose Program/Degree
				    <?php
					// loop through all the outcomes
					//	    if (!empty($programs)) {
					//		foreach ($programs as $program) :
					//		    echo $program . ", ";
					//		endforeach;
					//	    }
				    ?>
				  '
			    multiple>
		        <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />
		    
		    <!-- Choose Years -->
		    <select class="selectpicker" id="year-menu" data-style="btn-primary" title='Choose Year'>
		       <option data-hidden="true"></option>
		    </select>
		    <br />
		    <br />

		    <!-- Submit Button used to get the plan data from the database -->
		    <button type="submit" name="formGetPlan" value="formGetPlan" class="btn btn-success btn-md">Submit &raquo;</button>
		    <p></p>

		    <!-- Back to Main Button used to return to the main page -->
		    <a class="btn btn-primary btn-md" href="../mock">&laquo;<?php echo $this->translate ('Back to Main') ?>
		    </a>
		    <p></p>
		</div><!--close container-->
	    </form>
	</div><!--close column-->
    
	<!--column 2 Right side of the acreen-->
	<p></p>
	<div class="col-md-8">
	    <div class="table-responsive">
		<table class="table table-bordered table-striped">
		    <colgroup><col class="col-xs-8"></colgroup>
		    <div class="bs-example">
			<table class="table">
			    <!-- create header line -->
			    <h4>VIEW PLAN FOR: <?php echo $unit . ", " . displayPrograms($programs) . $year ?></h4>
			    <div class="controls">
				<div class="panel-group" id="accordion">
				    <div class="panel panel-default">
					<div class="panel-heading">
					    <h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Outcomes</a>
					    </h4>
					</div>

					<div id="collapseOne" class="panel-collapse collapse in">
					    <div class="panel-body">
						<?php
						    // loop through all the outcomes
						    $outcomeCount = 0;
							if (!empty($outcomes)) {
							    foreach ($outcomes as $outcome) :
								$outcomeCount++;
						?>
								<!-- display the outcome information -->
								<p><?php getCount($outcomeCount) ?>. <?php echo $outcome->getOutcomeText() ?></td></p>
						<?php
							    endforeach;
							}
						?>
					    </div>
					</div>
				    </div>
				</div>

				<!-- all the database attributes are listed below -->
				<div class="panel panel-default">
				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
						1. Describe assessment method.
					    </a>
					</h4>
				    </div>

				    <div id="collapseTwo" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['assessment_method']) ?>
					    </textarea>  
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
						2. Describe population assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseThree" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['population']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
						3. Describe sample size assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseFour" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['sample_size']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
						4. Describe assessment date assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseFive" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['assessment_date']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
						5. Describe cost assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseSix" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['cost']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
						6. Describe analysis type assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseSeven" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['analysis_type']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
						7. Describe administrator assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseEight" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['administrator']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseNine">
						8. Describe analysis method assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseNine" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['analysis_method']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTen">
						9. Describe scope assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseTen" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['scope']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">
						10. Describe feedback assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseEleven" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['feedback']) ?>
					    </textarea>      
					</div>
				    </div>

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve">
						11. Describe feedback flag assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseTwelve" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['feedback_flag']) ?>
					    </textarea>      
					</div>
				    </div>					    

				    <div class="panel-heading">
					<h4 class="panel-title">
					    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThirteen">
						12. Describe plan status flag assessed.
					    </a>
					</h4>
				    </div>

				    <div id="collapseThirteen" class="panel-collapse collapse">
					<div class="panel-body">
					    <textarea rows="6" cols="60" class="textbox" id="" name="">
						<?php echo $this->escapeHtml($plan['plan_status']) ?>
					    </textarea>      
					</div>
				    </div>					    

				</div>
			    </div> <!-- controls -->

			    <div id="divNoPrint2">
				<div>
				    <?php
					// loop through all the outcomes
					$planDocumentsCount = 0;
					if (!empty($planDocuments)) {
					    foreach ($planDocuments as $planDocument) :
						$planDocumentsCount++;
						
						// combine the file name and file ext
						$filename = $planDocument['file_name'] . "." . $planDocument['file_ext'];
				    ?>
						<!-- display the plan document information -->
						<p><?php getCount($planDocumentsCount)?>.
						
						<a  href="<?php echo $this->url('plans',
										 array('action'=>'downloadFile',
										'id' => $filename,
										));
							  ?>"
						>
						<?php echo $filename ?></a>
						<?php echo "  Description: ". $planDocument['file_description']?></p>
				    <?php
					    endforeach;
					}
				    ?>
				</div>
				
				<a class="btn btn-primary" href="<?php echo $this->url('plans', array('action'=>'index')); ?>">Back to Plans</a>&nbsp;
				<button type="button" class="btn btn-primary" onclick="printPage()">Print</button>&nbsp;  <!--window.print()-->
			    </div>
			</table>
		    </div><!-- bs-example -->
		</table>
	    </div>
	</div>
    </div>
</div>
    
<?php
    // All php functions
    function getValue($value)
    {
	echo "value=\"$value\"";
    }
	    
    function getCount($count)
    {
	echo $count;
    }
    
    // create a list of all the programs to display
    function displayPrograms($programs)
    {
	// create an all program label to be displayed to the user
	$allPrograms = "";
	if (!empty($programs)) {
	    foreach ($programs as $program) :
		$allPrograms = $allPrograms . $program . ", ";
	    endforeach;
	}
	return $allPrograms;
    }
?>
 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="../../js/bootstrap.min.js"></script>
<script src="../../js/bootstrap-rta.min.js"></script>
<script src="../../js/bootstrap-select.js"></script>
<script src="../../js/customPlan.js"></script>


<script>

// load actions based on user privileges
$(document).ready(function() {
     $.rta(); // load rta features - simplest implementation

   // clear selectorlist before adding unit/department options
   var oldSelections = $('#action-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   var actions = <?php print json_encode($useractions); ?>;
   for (var i = 0; i < actions.length; i++){
      $('#action-menu').append('<option>' + actions[i] + '</option>');
   }
   
   // call code to initialize the selectpicker
   // this must come after the options are initialized
   $('.selectpicker').selectpicker();
});

// update unit/department options based on actions
$(document).on('change', '#action-menu', function () {
   $action = $('#action-menu option:selected').val();
   // clear selectorlist before adding unit/department options
   var oldSelections = $('#unit-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   // data-hidden="true" shows title on button
   $('#unit-menu').append('<option  data-hidden="true"></option>');
   $('#unit-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getUnits')); ?>";
   urlform = urlform + '/' + $action;
     
   // asynchronous ajax code to populate unit/department selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(unitsJson){
         for (var i = 0; i < unitsJson.length; i++){
            $('#unit-menu').append('<option>' + unitsJson[i].id + '</option>');
         }
         $('#unit-menu').selectpicker('refresh');
      },
   });
});

// update program options based on unit/department
$(document).on('change', '#unit-menu', function () {
   $unit = $('#unit-menu option:selected').val();
   // clear selectorlist before adding program/degree options
   var oldSelections = $('#prog-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   $('#prog-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getPrograms')); ?>";
   urlform = urlform + '/' + $unit;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#prog-menu').append('<option>' + programsJson[i].name + '</option>');
         }
         $('#prog-menu').selectpicker('refresh');
      },
   });
});

// load all the year options after the unit/department & unit/department are selected
$(document).on('change', '#prog-menu', function () {
   // clear selectorlist before adding all the years
   var oldSelections = $('#year-menu option');
   for (var i = 0; i < oldSelections.length; i++){
      oldSelections.remove();
   }
   
   // data-hidden="true" shows title on button
   $('#year-menu').append('<option  data-hidden="true"></option>');
   $('#year-menu').selectpicker('refresh');
   
   // create url for redirect
   var urlform = "<?php echo $this->url('plans', array(
                                    'controller'=>'plans',
                                    'action'=>'getYears')); ?>";
   urlform = urlform;
   
   // asynchronous ajax code to populate program/degree selector
   $.ajax({
      url: urlform,
      type: "GET",
      dataType: "json",
      error : function(xhr, status, error) {
         console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
      },
      success: function(programsJson){
         for (var i = 0; i < programsJson.length; i++){
            $('#year-menu').append('<option>' + programsJson[i].year + '</option>');
         }
         $('#year-menu').selectpicker('refresh');
      },
   });
});
</script>		