<?php
    $title = 'View Assessment Plan';
    $this->headTitle($title);
?>

<?php
    // Init Form
    $form = $this->form;
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
?>

<!-- create the right side of the page -->
<div class="container">
    <center><h3>Assessment Plans-VIEW Specific Plan</h3></center>
   
    <p></p>  
    <div class="row">

	<p></p>
	<div class="col-md-8">
	    <div class="table-responsive">
		<table class="table table-bordered table-striped">
		    <colgroup><col class="col-xs-8"></colgroup>
		    <div class="bs-example">
			<table class="table">
			    <!-- create header line -->
			    <?php
				$label="VIEW PLAN FOR: ";
				echo "<h4>" . $label . $unit . ", " . $programs . ", " . $year . "</h4>";
			    ?>
			     
			    <div class="controls">
				
				<!-- begin creating the accordion -->
				<div class="panel-group" id="accordion">
				    
				    <!-- create the outcome display -->
				    <?php
					if (!empty($outcomes)) {
				    ?>				    
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseOutcomes">Outcomes</a>
						    </h4>
						</div>
	
						<div id="collapseOutcomes" class="panel-collapse collapse in">
						    <div class="panel-body">
							<?php
							    // loop through all the outcomes
							    $outcomeCount = 0;
								    foreach ($outcomes as $outcome) :
									$outcomeCount++;
							?>
									<!-- display the outcome information -->
									<p><?php echo $outcomeCount;?>. <?php echo $outcome->getOutcomeText() ?></p>
							<?php
								    endforeach;
							?>
						    </div>
						</div>
					    </div>
    
					    <!-- all the database attributes are listed below -->
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseAssessmentMethod">
							    Describe assessment method.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseAssessmentMethod" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['assessment_method']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapsePopulation">
							    Describe population assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapsePopulation" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['population']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseSampleSize">
							    Describe sample size assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseSampleSize" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['sample_size']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseAssessmentDate">
							    Describe assessment date assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseAssessmentDate" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['assessment_date']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseCost">
							    Describe cost assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseCost" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['cost']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
						
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseFundingFlag">
							    Are you requesting funding?
							</a>
						    </h4>
						</div>
	    
						<div id="collapseFundingFlag" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $fundingFlag = $plan['funding_flag'];
							    $label = "No";
							    if ($fundingFlag == 1) {
								$label = "Yes";
							    }
							    
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($label);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
						
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseAnalysisType">
							    Describe analysis type assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseAnalysisType" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['analysis_type']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseAdministrator">
							    Describe administrator assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseAdministrator" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['administrator']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseAnalysisMethod">
							    Describe analysis method assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseAnalysisMethod" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['analysis_method']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseScope">
							    Describe scope assessed.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseScope" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['scope']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>					    
							
					    </div>
				    <?php
					}
					else
					{
				    ?>
					    <!-- all the meta database attributes are listed below -->
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseMetaDescription">
							    Meta Description.
							</a>
						    </h4>
						</div>
	    
						<div id="collapseMetaDescription" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['meta_description']);
							    echo $this->formTextarea($elem);
							?>	
						    </div>
						</div>
					    </div>
				    <?php
					}
				    ?>
					    <!-- display all the feedback attributes -->
					    <div class="panel panel-success">  
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseFeedback">
							    Describe feedback assessed.
							</a>
						    </h4>
						</div>
			
						<div id="collapseFeedback" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $elem = $form->get('textFeedback');
							    $elem->setValue($plan['feedback_text']);
							    echo $this->formTextarea($elem);
							?>						
						    </div>
						</div>
			
						<div class="panel-heading">
						    <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseFeedbackFlag">
							    Describe feedback flag assessed.
							</a>
						    </h4>
						</div>
			
						<div id="collapseFeedbackFlag" class="panel-collapse collapse">
						    <div class="panel-body">
							<?php
							    $feedbackFlag = $plan['feedback'];
							    $elem = $form->get('feedbackFlag');
							    $elem->setValue($feedbackFlag);
							    echo $this->formRow($form->get('feedbackFlag'));
							?>						
						    </div>
						</div>
					    </div>
				    </div>
			    </div> <!-- controls -->

			    <!-- display all the plan documents and set them to no print -->
			    <div id="divNoPrint2">
				<div>
				    <?php
					// loop through all the plan documents
					$planDocumentsCount = 0;
					if (!empty($planDocuments)) {
					    foreach ($planDocuments as $planDocument) :
						$planDocumentsCount++;
						
						// combine the file name and file ext
						$filename = $planDocument['file_name'] . "." . $planDocument['file_ext'];
						
						//get the id
						$id = $planDocument['id']
				    ?>
						<!-- display the plan document information -->
						<p><?php echo $planDocumentsCount;?>.
						
						<a  href="<?php echo $this->url('plans',
										 array('action'=>'downloadFile',
										'id' => $id,
										));
							  ?>"
						>
						<?php echo $filename ?></a>
						<?php echo "  Description: ". $planDocument['file_description']?></p>
				    <?php
					    endforeach;
					}
				    ?>
				</div>
				
				<!-- create a print button -->
				<button type="button" class="btn btn-primary" onclick="printPage()">Print</button>&nbsp;  <!--window.print()-->
			    </div>
			</table>
		    </div>
		</table>
	    </div>
	</div>
    </div>
</div>