<?php
$title = 'Review Assessment Plans and Reports';
$this->headTitle($title);
?>	
<center><h3>Review Assessment Plans or Reports</h3>
 <div class="row">
 <div class="col-md-4">
     <!-- Dept typeahead -->
     <div class="container">
         <div class="input-group" >
             <p></p>
         </div><!-- /input-group -->
         <h6>Enter Department Name</h6>
         <div class="input-group">
             <input type="text" class="form-control" placeholder="Type ahead here...">
                 <span class="input-group-btn">
                     <button class="btn btn-primary" type="button">Enter</button>
                 </span>
         </div><!-- /input-group -->
         
     <!-- Prog/Degree dropdown -->
     <h6>Select Program/Degree</h6>
     <div class="input-group">
         <div class="input-group-btn">
             <button type="button" class="btn btn-primary dropdown-toggle"
             data-toggle="dropdown">Select
             <span class="caret"></span>
             </button>
             <ul class="dropdown-menu">
                 <li><a href="#">Computer Science/BS</a></li>
                 <li><a href="#">Computer Science/MS</a></li>
                 <li><a href="#">Computer Science/BS</a></li>
             </ul>
         </div>
         <input type="text" class="form-control" placeholder="Prog/Deg appears here">
     </div>
    <!-- Year  -->
    <h6>Select Academic year</h6>
    <div class="input-group">
         <div class="input-group-btn">
             <button type="button" class="btn btn-primary dropdown-toggle"
                     data-toggle="dropdown">2014-15
                 <span class="caret"></span>
             </button>
             <ul class="dropdown-menu" >
                 <li><a href="#">2015-16</a></li>
                 <li><a href="#">2016-17</a></li>
                 <li><a href="#">2017-18</a></li>
             </ul>
         </div>
         <input type="text" class="form-control" placeholder="Year appears here">
    </div>
     <p></p>
    <a class="btn btn-primary btn-lg" href="#"><?php echo $this->translate
     ('Find Plan') ?> &raquo;</a>
     </div><!--close container-->
 </div><!--close column-->
 
 <!--column 2-->
 <p>This is where the plan or report will pop up with a feedback box.</p>
 
                                 
                                         
 <script src="js/jquery-1.8.3.min.js"></script>
 <script src="js/bootstrap3-typeahead.js"></script>
 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 <script src="https://code.jquery.com/jquery.js"></script>
 <!-- Include all compiled plugins (below), or include individual files as needed -->
 <script src="js/bootstrap.min.js"></script>
