<?php

$title = 'Academic Assessment Home';
$this->headTitle($title);
?>
<p></p>
<html><body>
    <div class="container">
        <center><h3>NCC Academic Assessment Portal</h3>
          
            <!-- Student Outcomes button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'modifyso'));?>"><?php echo $this->translate
            ('Outcomes') ?> &raquo;</a>
            <p></p>
            <!-- Plans button -->
            
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'plansplain'));?>"><?php echo $this->translate
            ('&nbsp;&nbsp;&nbsp; Plans &nbsp; &nbsp;') ?> &raquo;</a>
            <p></p>
            <!-- Reports button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'reportsplain'));?>"><?php echo $this->translate
            ('&nbsp;&nbsp;Reports&nbsp;&nbsp;') ?> &raquo;</a>
            <p></p>
            <!-- Admin button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('mock', array('action'=>'adminplain'));?>"><?php echo $this->translate
            ('&nbsp;&nbsp;Admin&nbsp;&nbsp;') ?> &raquo;</a>
            <p></p>
        </center>
    </div>
   
</html>