<?php

$title = 'Academic Assessment Login';
$this->headTitle($title);


$form = $this->form;
$form->setAttribute('action', 'index/authenticate');
$form->prepare();

echo '<br>';
echo $message;
echo '<br><br>';
echo 'Please log in with your NCC user ID and password';


echo '<br><br><br>';
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);

?>