<?php

$title = 'Academic Assessment Login';
$this->headTitle($title);


$form = $this->form;
$form->setAttribute('action', 'index/authenticate');
$form->prepare();
?>

<center>
<br>
<?php echo $message; ?>
<br><br>
Please log in with your NCC user ID and password
<br><br><br>

<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
?>
</center>