<?php
// module/Application/view/application/index/index.phtml:

$title = 'NCC Assessment Home';
$this->headTitle($title);
?>
<p></p>
<html><body>
    <div class="container">
        <center><h3>NCC Assessment Portal</h3>
          
            <!-- Student Outcomes button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('outcomes', array('action'=>'index'));?>"><?php echo $this->translate
            ('Outcomes') ?> &raquo;</a>
            <p></p>
            <!-- Plans button -->
            
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('plans', array('action'=>'index'));?>"><?php echo $this->translate
            ('&nbsp;&nbsp;&nbsp; Plans &nbsp; &nbsp;') ?> &raquo;</a>
            <p></p>
            <!-- Reports button -->
            <a class="btn btn-primary btn-lg" href="<?php echo $this->url
            ('reports', array('action'=>'index'));?>"><?php echo $this->translate
            ('&nbsp;&nbsp;Reports&nbsp;&nbsp;') ?> &raquo;</a>
            <p></p>
        </center>
    </div>
   
</html>