<?php
$form = $this->form;
$form->setAttribute('action', $this->url('unit', array('action' => $action,'id'=>$this->id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="control-group col-md-12">  
    <div class="control-group">
    <h2>Unit</h2>   
    <div class="form-group">
        <?php echo $this->formLabel($form->get('id')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('type')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formInput($form->get('type')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('active_flag')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formCheckbox($form->get('active_flag')); ?>
    </div>      

    </div>
</div>
<div class="control-group col-md-12">  
    <h2>Chair/Assessors</h2> 
      <div class="form-group">
        <?php echo $this->formLabel($form->get('assessor_1')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('assessor_1')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('assessor_2')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('assessor_2')); ?>
    </div>     
</div>
<div class="control-group col-md-12">  
    <h2>Liason(s)</h2> 
      <div class="form-group">
        <?php echo $this->formLabel($form->get('liaison_1')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('liaison_1')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('liaison_2')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('liaison_2')); ?>
    </div>     
</div>
<div class="control-group col-md-12">     
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>