<?php
// module/Admin/view/admin/unit/index.phtml:
$title = 'Units';
$this->headTitle($title);
?>
<?php echo $this->partial('admin/admin/menu.phtml', array('active' => 'unit')); ?>
<div class="col-md-12">
    <div class="col-mid-10">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-mid-2">
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url('unit', array('action' => 'add'));
?>"><?php echo $this->translate('Add Unit') ?> &raquo;</a>
    </div>

</div>


<div class="col-md-12">
    <h3>All Units</h3>
    <div class="table-responsive">
        <colgroup>
            <col class="col-xs-8">
        </colgroup>
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Created Date</th>
                    <th>Created User ID</th>
                    <th>Deactivated Date</th>
                    <th>Deactivated User ID</th>
                    <th>Active</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $unit) : ?>
                    <tr class="active">
                        <td><?php echo $this->escapeHtml($unit->id); ?></td>
                        <td><?php echo $this->escapeHtml($unit->type); ?></td>
                        <td><?php echo $this->escapeHtml($unit->created_ts); ?></td>
                        <td><?php echo $this->escapeHtml($unit->created_user); ?></td>
                        <td><?php echo $this->escapeHtml($unit->deactivated_ts); ?></td>
                        <td><?php echo $this->escapeHtml($unit->deactivated_user); ?></td>
                        <td><?php echo $this->escapeHtml($unit->active_flag); ?></td>   
                        <td>
                            <a class="btn btn-primary btn-xs" href="<?php echo $this->url('unit', array('action' => 'edit', 'id' => $unit->id));
                ?>"><?php echo $this->translate('Edit') ?> &raquo;</a>
                            <a class="btn btn-warning btn-xs" href="<?php echo $this->url('unit', array('action' => 'delete', 'id' => $unit->id));
                           ?>"><?php echo $this->translate('Delete') ?> &raquo;</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                $this->paginator, // the paginator object
                'sliding', // the scrolling style; 
                //see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                array('admin/unit/controls.phtml', 'Unit'), // the partial to use to render the control
                array('route' => 'unit')// the route to link to when a user clicks a control link
        );
        ?>
    </div>
</div>

